// Command generate reads openapi.json and emits the generated parts of the
// SDK: resources_gen.go (the resource surface), endpoints_gen_test.go (one
// test per operation), and the README's API reference section.
//
// Run from the repository root: go run ./scripts/generate
package main

import (
	"fmt"
	"go/format"
	"log"
	"os"
	"strings"
)

// goArgs renders the Go parameter list shared by resources and tests.
func goArgs(m *methodSpec) string {
	var b strings.Builder
	b.WriteString("ctx context.Context")
	for _, p := range m.PathParams {
		b.WriteString(", " + p.Arg + " string")
	}
	if m.HasBody {
		b.WriteString(", body map[string]any")
	}
	if m.HasQuery {
		b.WriteString(", query map[string]string")
	}
	b.WriteString(", opts *RequestOptions")
	return b.String()
}

// pathExpr renders the Go expression building the request path.
func pathExpr(m *methodSpec) string {
	if len(m.PathParams) == 0 {
		return fmt.Sprintf("%q", m.Path)
	}
	expr := m.Path
	for _, p := range m.PathParams {
		expr = strings.ReplaceAll(expr, "{"+p.Raw+"}", `"+url.PathEscape(`+p.Arg+`)+"`)
	}
	expr = `"` + expr + `"`
	expr = strings.TrimPrefix(expr, `""+`)
	expr = strings.TrimSuffix(expr, `+""`)
	return expr
}

func writeResources(resources []*resourceSpec) {
	var b strings.Builder
	b.WriteString(`// Code generated by scripts/generate from openapi.json. DO NOT EDIT.

package smartlyq

import (
	"context"
	"net/url"
)

// resources holds one field per API resource group; it is embedded in Client.
type resources struct {
`)
	for _, r := range resources {
		fmt.Fprintf(&b, "\t%s *%s\n", r.Field, r.StructName)
	}
	b.WriteString("}\n\nfunc (c *Client) initResources() {\n")
	for _, r := range resources {
		fmt.Fprintf(&b, "\tc.%s = &%s{client: c}\n", r.Field, r.StructName)
	}
	b.WriteString("}\n")

	for _, r := range resources {
		fmt.Fprintf(&b, "\n// %s groups the %s endpoints.\ntype %s struct{ client *Client }\n", r.StructName, r.Tag, r.StructName)
		for _, m := range r.Methods {
			bodyArg, queryArg := "nil", "nil"
			if m.HasBody {
				bodyArg = "body"
			}
			if m.HasQuery {
				queryArg = "query"
			}
			fmt.Fprintf(&b, "\n// %s - %s.\n//\n// %s %s\n", m.Name, strings.TrimRight(m.Summary, "."), m.HTTPMethod, m.Path)
			fmt.Fprintf(&b, "func (r *%s) %s(%s) (*Envelope, error) {\n", r.StructName, m.Name, goArgs(m))
			fmt.Fprintf(&b, "\treturn r.client.do(ctx, %q, %s, %s, %s, opts)\n}\n", m.HTTPMethod, pathExpr(m), queryArg, bodyArg)
		}
	}
	mustWrite("resources_gen.go", b.String())
}

func writeEndpointTests(resources []*resourceSpec) {
	var b strings.Builder
	b.WriteString(`// Code generated by scripts/generate from openapi.json. DO NOT EDIT.

package smartlyq

import (
	"context"
	"net/http"
	"net/http/httptest"
	"testing"
)

// assertEndpoint runs call against a stub server and asserts the SDK hit the
// expected HTTP method and path.
func assertEndpoint(t *testing.T, wantMethod, wantPath string, call func(c *Client) error) {
	t.Helper()
	var gotMethod, gotPath string
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		gotMethod, gotPath = r.Method, r.URL.Path
		w.Header().Set("Content-Type", "application/json")
		_, _ = w.Write([]byte(` + "`" + `{"success":true,"data":{}}` + "`" + `))
	}))
	defer srv.Close()
	c := NewClient("sqk_test_xxxxxxxxxxxx", WithBaseURL(srv.URL), WithMaxRetries(0))
	if err := call(c); err != nil {
		t.Fatalf("request failed: %v", err)
	}
	if gotMethod != wantMethod {
		t.Errorf("method = %q, want %q", gotMethod, wantMethod)
	}
	if gotPath != wantPath {
		t.Errorf("path = %q, want %q", gotPath, wantPath)
	}
}
`)
	for _, r := range resources {
		for _, m := range r.Methods {
			args := []string{"context.Background()"}
			wantPath := m.Path
			for _, p := range m.PathParams {
				args = append(args, fmt.Sprintf("%q", "test-"+p.Arg))
				wantPath = strings.ReplaceAll(wantPath, "{"+p.Raw+"}", "test-"+p.Arg)
			}
			if m.HasBody {
				args = append(args, "map[string]any{}")
			}
			if m.HasQuery {
				args = append(args, "nil")
			}
			args = append(args, "nil")
			fmt.Fprintf(&b, "\nfunc Test%s%s(t *testing.T) {\n", r.Field, m.Name)
			fmt.Fprintf(&b, "\tassertEndpoint(t, %q, %q, func(c *Client) error {\n", m.HTTPMethod, wantPath)
			fmt.Fprintf(&b, "\t\t_, err := c.%s.%s(%s)\n\t\treturn err\n\t})\n}\n", r.Field, m.Name, strings.Join(args, ", "))
		}
	}
	mustWrite("endpoints_gen_test.go", b.String())
}

func writeReadmeReference(resources []*resourceSpec) {
	const begin = "<!-- BEGIN GENERATED REFERENCE -->"
	const end = "<!-- END GENERATED REFERENCE -->"
	readme, err := os.ReadFile("README.md")
	if err != nil {
		log.Fatalf("reading README.md: %v", err)
	}
	content := string(readme)
	start := strings.Index(content, begin)
	stop := strings.Index(content, end)
	if start == -1 || stop == -1 || stop < start {
		log.Fatal("README.md is missing the generated-reference markers")
	}

	var b strings.Builder
	b.WriteString(begin + "\n")
	for _, r := range resources {
		fmt.Fprintf(&b, "\n### %s\n\n", r.Tag)
		b.WriteString("| Method | Endpoint | Description |\n| --- | --- | --- |\n")
		for _, m := range r.Methods {
			args := []string{"ctx"}
			for _, p := range m.PathParams {
				args = append(args, p.Arg)
			}
			if m.HasBody {
				args = append(args, "body")
			}
			if m.HasQuery {
				args = append(args, "query")
			}
			fmt.Fprintf(&b, "| `client.%s.%s(%s)` | `%s %s` | %s |\n",
				r.Field, m.Name, strings.Join(args, ", "), m.HTTPMethod, m.Path, m.Summary)
		}
	}
	b.WriteString(end)
	mustWrite("README.md", content[:start]+b.String()+content[stop+len(end):])
}

func mustWrite(path, content string) {
	data := []byte(content)
	if strings.HasSuffix(path, ".go") {
		formatted, err := format.Source(data)
		if err != nil {
			log.Fatalf("formatting %s: %v", path, err)
		}
		data = formatted
	}
	if err := os.WriteFile(path, data, 0o644); err != nil {
		log.Fatalf("writing %s: %v", path, err)
	}
	fmt.Printf("wrote %s\n", path)
}

func main() {
	resources := buildModel("openapi.json")
	total := 0
	for _, r := range resources {
		total += len(r.Methods)
	}
	fmt.Printf("model: %d resources, %d operations\n", len(resources), total)
	writeResources(resources)
	writeEndpointTests(resources)
	writeReadmeReference(resources)
}
