// Code generated by scripts/generate from openapi.json. DO NOT EDIT.

package smartlyq

import (
	"context"
	"net/http"
	"net/http/httptest"
	"testing"
)

// assertEndpoint runs call against a stub server and asserts the SDK hit the
// expected HTTP method and path.
func assertEndpoint(t *testing.T, wantMethod, wantPath string, call func(c *Client) error) {
	t.Helper()
	var gotMethod, gotPath string
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		gotMethod, gotPath = r.Method, r.URL.Path
		w.Header().Set("Content-Type", "application/json")
		_, _ = w.Write([]byte(`{"success":true,"data":{}}`))
	}))
	defer srv.Close()
	c := NewClient("sqk_test_xxxxxxxxxxxx", WithBaseURL(srv.URL), WithMaxRetries(0))
	if err := call(c); err != nil {
		t.Fatalf("request failed: %v", err)
	}
	if gotMethod != wantMethod {
		t.Errorf("method = %q, want %q", gotMethod, wantMethod)
	}
	if gotPath != wantPath {
		t.Errorf("path = %q, want %q", gotPath, wantPath)
	}
}

func TestAccountGetMe(t *testing.T) {
	assertEndpoint(t, "GET", "/me", func(c *Client) error {
		_, err := c.Account.GetMe(context.Background(), nil)
		return err
	})
}

func TestAccountGetMeUsage(t *testing.T) {
	assertEndpoint(t, "GET", "/me/usage", func(c *Client) error {
		_, err := c.Account.GetMeUsage(context.Background(), nil, nil)
		return err
	})
}

func TestAccountGetMeBalance(t *testing.T) {
	assertEndpoint(t, "GET", "/me/balance", func(c *Client) error {
		_, err := c.Account.GetMeBalance(context.Background(), nil)
		return err
	})
}

func TestCaptainSendMessage(t *testing.T) {
	assertEndpoint(t, "POST", "/captain/messages", func(c *Client) error {
		_, err := c.Captain.SendMessage(context.Background(), map[string]any{}, nil)
		return err
	})
}

func TestCaptainListConversations(t *testing.T) {
	assertEndpoint(t, "GET", "/captain/conversations", func(c *Client) error {
		_, err := c.Captain.ListConversations(context.Background(), nil, nil)
		return err
	})
}

func TestCaptainGetConversation(t *testing.T) {
	assertEndpoint(t, "GET", "/captain/conversations/test-conversationId", func(c *Client) error {
		_, err := c.Captain.GetConversation(context.Background(), "test-conversationId", nil)
		return err
	})
}

func TestAnalyticsGetOverview(t *testing.T) {
	assertEndpoint(t, "GET", "/analytics/overview", func(c *Client) error {
		_, err := c.Analytics.GetOverview(context.Background(), nil, nil)
		return err
	})
}

func TestAnalyticsGetPosts(t *testing.T) {
	assertEndpoint(t, "GET", "/analytics/posts", func(c *Client) error {
		_, err := c.Analytics.GetPosts(context.Background(), nil, nil)
		return err
	})
}

func TestAnalyticsGetAccount(t *testing.T) {
	assertEndpoint(t, "GET", "/analytics/accounts/test-accountId", func(c *Client) error {
		_, err := c.Analytics.GetAccount(context.Background(), "test-accountId", nil, nil)
		return err
	})
}

func TestAnalyticsDailyMetrics(t *testing.T) {
	assertEndpoint(t, "GET", "/analytics/daily-metrics", func(c *Client) error {
		_, err := c.Analytics.DailyMetrics(context.Background(), nil, nil)
		return err
	})
}

func TestAnalyticsBestTime(t *testing.T) {
	assertEndpoint(t, "GET", "/analytics/best-time", func(c *Client) error {
		_, err := c.Analytics.BestTime(context.Background(), nil, nil)
		return err
	})
}

func TestAnalyticsContentDecay(t *testing.T) {
	assertEndpoint(t, "GET", "/analytics/content-decay", func(c *Client) error {
		_, err := c.Analytics.ContentDecay(context.Background(), nil, nil)
		return err
	})
}

func TestAnalyticsPostingFrequency(t *testing.T) {
	assertEndpoint(t, "GET", "/analytics/posting-frequency", func(c *Client) error {
		_, err := c.Analytics.PostingFrequency(context.Background(), nil, nil)
		return err
	})
}

func TestAnalyticsPostTimeline(t *testing.T) {
	assertEndpoint(t, "GET", "/analytics/posts/test-postId/timeline", func(c *Client) error {
		_, err := c.Analytics.PostTimeline(context.Background(), "test-postId", nil)
		return err
	})
}

func TestAnalyticsInboxVolume(t *testing.T) {
	assertEndpoint(t, "GET", "/analytics/inbox/volume", func(c *Client) error {
		_, err := c.Analytics.InboxVolume(context.Background(), nil, nil)
		return err
	})
}

func TestAnalyticsInboxHeatmap(t *testing.T) {
	assertEndpoint(t, "GET", "/analytics/inbox/heatmap", func(c *Client) error {
		_, err := c.Analytics.InboxHeatmap(context.Background(), nil, nil)
		return err
	})
}

func TestAnalyticsInboxSourceBreakdown(t *testing.T) {
	assertEndpoint(t, "GET", "/analytics/inbox/source-breakdown", func(c *Client) error {
		_, err := c.Analytics.InboxSourceBreakdown(context.Background(), nil, nil)
		return err
	})
}

func TestAnalyticsInboxResponseTime(t *testing.T) {
	assertEndpoint(t, "GET", "/analytics/inbox/response-time", func(c *Client) error {
		_, err := c.Analytics.InboxResponseTime(context.Background(), nil, nil)
		return err
	})
}

func TestAnalyticsInboxTopAccounts(t *testing.T) {
	assertEndpoint(t, "GET", "/analytics/inbox/top-accounts", func(c *Client) error {
		_, err := c.Analytics.InboxTopAccounts(context.Background(), nil, nil)
		return err
	})
}

func TestAnalyticsInboxConversations(t *testing.T) {
	assertEndpoint(t, "GET", "/analytics/inbox/conversations", func(c *Client) error {
		_, err := c.Analytics.InboxConversations(context.Background(), nil, nil)
		return err
	})
}

func TestAnalyticsInboxConversationDetail(t *testing.T) {
	assertEndpoint(t, "GET", "/analytics/inbox/conversations/test-conversationId", func(c *Client) error {
		_, err := c.Analytics.InboxConversationDetail(context.Background(), "test-conversationId", nil)
		return err
	})
}

func TestArticlesGenerate(t *testing.T) {
	assertEndpoint(t, "POST", "/articles/generate", func(c *Client) error {
		_, err := c.Articles.Generate(context.Background(), map[string]any{}, nil)
		return err
	})
}

func TestArticlesList(t *testing.T) {
	assertEndpoint(t, "GET", "/articles", func(c *Client) error {
		_, err := c.Articles.List(context.Background(), nil, nil)
		return err
	})
}

func TestArticlesGet(t *testing.T) {
	assertEndpoint(t, "GET", "/articles/test-articleId", func(c *Client) error {
		_, err := c.Articles.Get(context.Background(), "test-articleId", nil)
		return err
	})
}

func TestArticlesDelete(t *testing.T) {
	assertEndpoint(t, "DELETE", "/articles/test-articleId", func(c *Client) error {
		_, err := c.Articles.Delete(context.Background(), "test-articleId", nil)
		return err
	})
}

func TestAudioTextToSpeech(t *testing.T) {
	assertEndpoint(t, "POST", "/audio/text-to-speech", func(c *Client) error {
		_, err := c.Audio.TextToSpeech(context.Background(), map[string]any{}, nil)
		return err
	})
}

func TestAudioSpeechToText(t *testing.T) {
	assertEndpoint(t, "POST", "/audio/speech-to-text", func(c *Client) error {
		_, err := c.Audio.SpeechToText(context.Background(), map[string]any{}, nil)
		return err
	})
}

func TestAudioGet(t *testing.T) {
	assertEndpoint(t, "GET", "/audio/test-audioId", func(c *Client) error {
		_, err := c.Audio.Get(context.Background(), "test-audioId", nil)
		return err
	})
}

func TestAutomationsList(t *testing.T) {
	assertEndpoint(t, "GET", "/automations", func(c *Client) error {
		_, err := c.Automations.List(context.Background(), nil, nil)
		return err
	})
}

func TestAutomationsGet(t *testing.T) {
	assertEndpoint(t, "GET", "/automations/test-automationId", func(c *Client) error {
		_, err := c.Automations.Get(context.Background(), "test-automationId", nil)
		return err
	})
}

func TestAutomationsActivate(t *testing.T) {
	assertEndpoint(t, "POST", "/automations/test-automationId/activate", func(c *Client) error {
		_, err := c.Automations.Activate(context.Background(), "test-automationId", nil)
		return err
	})
}

func TestAutomationsDeactivate(t *testing.T) {
	assertEndpoint(t, "POST", "/automations/test-automationId/deactivate", func(c *Client) error {
		_, err := c.Automations.Deactivate(context.Background(), "test-automationId", nil)
		return err
	})
}

func TestAutomationsTrigger(t *testing.T) {
	assertEndpoint(t, "POST", "/automations/test-automationId/trigger", func(c *Client) error {
		_, err := c.Automations.Trigger(context.Background(), "test-automationId", map[string]any{}, nil)
		return err
	})
}

func TestAutomationsListRuns(t *testing.T) {
	assertEndpoint(t, "GET", "/automations/test-automationId/runs", func(c *Client) error {
		_, err := c.Automations.ListRuns(context.Background(), "test-automationId", nil, nil)
		return err
	})
}

func TestAutomationsGetRun(t *testing.T) {
	assertEndpoint(t, "GET", "/automations/test-automationId/runs/test-runId", func(c *Client) error {
		_, err := c.Automations.GetRun(context.Background(), "test-automationId", "test-runId", nil)
		return err
	})
}

func TestChatbotsList(t *testing.T) {
	assertEndpoint(t, "GET", "/chatbots", func(c *Client) error {
		_, err := c.Chatbots.List(context.Background(), nil, nil)
		return err
	})
}

func TestChatbotsCreate(t *testing.T) {
	assertEndpoint(t, "POST", "/chatbots", func(c *Client) error {
		_, err := c.Chatbots.Create(context.Background(), map[string]any{}, nil)
		return err
	})
}

func TestChatbotsGet(t *testing.T) {
	assertEndpoint(t, "GET", "/chatbots/test-id", func(c *Client) error {
		_, err := c.Chatbots.Get(context.Background(), "test-id", nil)
		return err
	})
}

func TestChatbotsUpdate(t *testing.T) {
	assertEndpoint(t, "PATCH", "/chatbots/test-id", func(c *Client) error {
		_, err := c.Chatbots.Update(context.Background(), "test-id", map[string]any{}, nil)
		return err
	})
}

func TestChatbotsDelete(t *testing.T) {
	assertEndpoint(t, "DELETE", "/chatbots/test-id", func(c *Client) error {
		_, err := c.Chatbots.Delete(context.Background(), "test-id", nil)
		return err
	})
}

func TestChatbotsTrain(t *testing.T) {
	assertEndpoint(t, "POST", "/chatbots/test-id/train", func(c *Client) error {
		_, err := c.Chatbots.Train(context.Background(), "test-id", nil)
		return err
	})
}

func TestChatbotsGetTrainStatus(t *testing.T) {
	assertEndpoint(t, "GET", "/chatbots/test-id/train-status", func(c *Client) error {
		_, err := c.Chatbots.GetTrainStatus(context.Background(), "test-id", nil)
		return err
	})
}

func TestChatbotsSendMessage(t *testing.T) {
	assertEndpoint(t, "POST", "/chatbots/test-id/messages", func(c *Client) error {
		_, err := c.Chatbots.SendMessage(context.Background(), "test-id", map[string]any{}, nil)
		return err
	})
}

func TestChatbotsListConversations(t *testing.T) {
	assertEndpoint(t, "GET", "/chatbots/test-id/conversations", func(c *Client) error {
		_, err := c.Chatbots.ListConversations(context.Background(), "test-id", nil, nil)
		return err
	})
}

func TestChatbotsGetConversationMessages(t *testing.T) {
	assertEndpoint(t, "GET", "/chatbots/test-id/conversations/test-convId/messages", func(c *Client) error {
		_, err := c.Chatbots.GetConversationMessages(context.Background(), "test-id", "test-convId", nil)
		return err
	})
}

func TestCommentsList(t *testing.T) {
	assertEndpoint(t, "GET", "/social/comments", func(c *Client) error {
		_, err := c.Comments.List(context.Background(), nil, nil)
		return err
	})
}

func TestCommentsReplyTo(t *testing.T) {
	assertEndpoint(t, "POST", "/social/comments/test-commentId/reply", func(c *Client) error {
		_, err := c.Comments.ReplyTo(context.Background(), "test-commentId", map[string]any{}, nil)
		return err
	})
}

func TestCommentsHide(t *testing.T) {
	assertEndpoint(t, "POST", "/social/comments/test-commentId/hide", func(c *Client) error {
		_, err := c.Comments.Hide(context.Background(), "test-commentId", nil)
		return err
	})
}

func TestCommentsDelete(t *testing.T) {
	assertEndpoint(t, "DELETE", "/social/comments/test-commentId", func(c *Client) error {
		_, err := c.Comments.Delete(context.Background(), "test-commentId", nil)
		return err
	})
}

func TestContentRewrite(t *testing.T) {
	assertEndpoint(t, "POST", "/content/rewrite", func(c *Client) error {
		_, err := c.Content.Rewrite(context.Background(), map[string]any{}, nil)
		return err
	})
}

func TestContentGenerateCaption(t *testing.T) {
	assertEndpoint(t, "POST", "/content/caption", func(c *Client) error {
		_, err := c.Content.GenerateCaption(context.Background(), map[string]any{}, nil)
		return err
	})
}

func TestCRMDeleteContact(t *testing.T) {
	assertEndpoint(t, "DELETE", "/contacts/test-id", func(c *Client) error {
		_, err := c.CRM.DeleteContact(context.Background(), "test-id", nil)
		return err
	})
}

func TestCRMBulkImportContacts(t *testing.T) {
	assertEndpoint(t, "POST", "/contacts/bulk", func(c *Client) error {
		_, err := c.CRM.BulkImportContacts(context.Background(), map[string]any{}, nil)
		return err
	})
}

func TestContactsList(t *testing.T) {
	assertEndpoint(t, "GET", "/contacts", func(c *Client) error {
		_, err := c.Contacts.List(context.Background(), nil, nil)
		return err
	})
}

func TestContactsCreate(t *testing.T) {
	assertEndpoint(t, "POST", "/contacts", func(c *Client) error {
		_, err := c.Contacts.Create(context.Background(), map[string]any{}, nil)
		return err
	})
}

func TestContactsGet(t *testing.T) {
	assertEndpoint(t, "GET", "/contacts/test-id", func(c *Client) error {
		_, err := c.Contacts.Get(context.Background(), "test-id", nil)
		return err
	})
}

func TestContactsUpdate(t *testing.T) {
	assertEndpoint(t, "PATCH", "/contacts/test-id", func(c *Client) error {
		_, err := c.Contacts.Update(context.Background(), "test-id", map[string]any{}, nil)
		return err
	})
}

func TestContactsAddTags(t *testing.T) {
	assertEndpoint(t, "POST", "/contacts/test-id/tags", func(c *Client) error {
		_, err := c.Contacts.AddTags(context.Background(), "test-id", map[string]any{}, nil)
		return err
	})
}

func TestContactsRemoveTags(t *testing.T) {
	assertEndpoint(t, "DELETE", "/contacts/test-id/tags", func(c *Client) error {
		_, err := c.Contacts.RemoveTags(context.Background(), "test-id", map[string]any{}, nil)
		return err
	})
}

func TestContactsListNotes(t *testing.T) {
	assertEndpoint(t, "GET", "/contacts/test-id/notes", func(c *Client) error {
		_, err := c.Contacts.ListNotes(context.Background(), "test-id", nil)
		return err
	})
}

func TestContactsAddNote(t *testing.T) {
	assertEndpoint(t, "POST", "/contacts/test-id/notes", func(c *Client) error {
		_, err := c.Contacts.AddNote(context.Background(), "test-id", map[string]any{}, nil)
		return err
	})
}

func TestContactsEnroll(t *testing.T) {
	assertEndpoint(t, "POST", "/contacts/test-id/enroll", func(c *Client) error {
		_, err := c.Contacts.Enroll(context.Background(), "test-id", map[string]any{}, nil)
		return err
	})
}

func TestContactsAddMessage(t *testing.T) {
	assertEndpoint(t, "POST", "/contacts/test-id/messages", func(c *Client) error {
		_, err := c.Contacts.AddMessage(context.Background(), "test-id", map[string]any{}, nil)
		return err
	})
}

func TestCustomFieldsList(t *testing.T) {
	assertEndpoint(t, "GET", "/custom-fields", func(c *Client) error {
		_, err := c.CustomFields.List(context.Background(), nil)
		return err
	})
}

func TestCustomFieldsCreate(t *testing.T) {
	assertEndpoint(t, "POST", "/custom-fields", func(c *Client) error {
		_, err := c.CustomFields.Create(context.Background(), map[string]any{}, nil)
		return err
	})
}

func TestCustomFieldsDelete(t *testing.T) {
	assertEndpoint(t, "DELETE", "/custom-fields/test-id", func(c *Client) error {
		_, err := c.CustomFields.Delete(context.Background(), "test-id", nil)
		return err
	})
}

func TestOpportunitiesListPipelines(t *testing.T) {
	assertEndpoint(t, "GET", "/pipelines", func(c *Client) error {
		_, err := c.Opportunities.ListPipelines(context.Background(), nil)
		return err
	})
}

func TestOpportunitiesCreatePipeline(t *testing.T) {
	assertEndpoint(t, "POST", "/pipelines", func(c *Client) error {
		_, err := c.Opportunities.CreatePipeline(context.Background(), map[string]any{}, nil)
		return err
	})
}

func TestOpportunitiesList(t *testing.T) {
	assertEndpoint(t, "GET", "/opportunities", func(c *Client) error {
		_, err := c.Opportunities.List(context.Background(), nil, nil)
		return err
	})
}

func TestOpportunitiesCreate(t *testing.T) {
	assertEndpoint(t, "POST", "/opportunities", func(c *Client) error {
		_, err := c.Opportunities.Create(context.Background(), map[string]any{}, nil)
		return err
	})
}

func TestOpportunitiesGet(t *testing.T) {
	assertEndpoint(t, "GET", "/opportunities/test-id", func(c *Client) error {
		_, err := c.Opportunities.Get(context.Background(), "test-id", nil)
		return err
	})
}

func TestOpportunitiesUpdate(t *testing.T) {
	assertEndpoint(t, "PATCH", "/opportunities/test-id", func(c *Client) error {
		_, err := c.Opportunities.Update(context.Background(), "test-id", map[string]any{}, nil)
		return err
	})
}

func TestOpportunitiesDelete(t *testing.T) {
	assertEndpoint(t, "DELETE", "/opportunities/test-id", func(c *Client) error {
		_, err := c.Opportunities.Delete(context.Background(), "test-id", nil)
		return err
	})
}

func TestOpportunitiesUpdateStatus(t *testing.T) {
	assertEndpoint(t, "POST", "/opportunities/test-id/status", func(c *Client) error {
		_, err := c.Opportunities.UpdateStatus(context.Background(), "test-id", map[string]any{}, nil)
		return err
	})
}

func TestMessagesListConversations(t *testing.T) {
	assertEndpoint(t, "GET", "/social/conversations", func(c *Client) error {
		_, err := c.Messages.ListConversations(context.Background(), nil, nil)
		return err
	})
}

func TestMessagesList(t *testing.T) {
	assertEndpoint(t, "GET", "/social/conversations/test-conversationId/messages", func(c *Client) error {
		_, err := c.Messages.List(context.Background(), "test-conversationId", nil, nil)
		return err
	})
}

func TestMessagesSend(t *testing.T) {
	assertEndpoint(t, "POST", "/social/conversations/test-conversationId/messages", func(c *Client) error {
		_, err := c.Messages.Send(context.Background(), "test-conversationId", map[string]any{}, nil)
		return err
	})
}

func TestMessagesMarkConversationRead(t *testing.T) {
	assertEndpoint(t, "POST", "/social/conversations/test-conversationId/read", func(c *Client) error {
		_, err := c.Messages.MarkConversationRead(context.Background(), "test-conversationId", nil)
		return err
	})
}

func TestImagesGenerate(t *testing.T) {
	assertEndpoint(t, "POST", "/images/generate", func(c *Client) error {
		_, err := c.Images.Generate(context.Background(), map[string]any{}, nil)
		return err
	})
}

func TestImagesList(t *testing.T) {
	assertEndpoint(t, "GET", "/images", func(c *Client) error {
		_, err := c.Images.List(context.Background(), nil, nil)
		return err
	})
}

func TestImagesGet(t *testing.T) {
	assertEndpoint(t, "GET", "/images/test-imageId", func(c *Client) error {
		_, err := c.Images.Get(context.Background(), "test-imageId", nil)
		return err
	})
}

func TestImagesDelete(t *testing.T) {
	assertEndpoint(t, "DELETE", "/images/test-imageId", func(c *Client) error {
		_, err := c.Images.Delete(context.Background(), "test-imageId", nil)
		return err
	})
}

func TestJobsList(t *testing.T) {
	assertEndpoint(t, "GET", "/jobs", func(c *Client) error {
		_, err := c.Jobs.List(context.Background(), nil, nil)
		return err
	})
}

func TestJobsGet(t *testing.T) {
	assertEndpoint(t, "GET", "/jobs/test-jobId", func(c *Client) error {
		_, err := c.Jobs.Get(context.Background(), "test-jobId", nil)
		return err
	})
}

func TestJobsCancel(t *testing.T) {
	assertEndpoint(t, "POST", "/jobs/test-jobId/cancel", func(c *Client) error {
		_, err := c.Jobs.Cancel(context.Background(), "test-jobId", map[string]any{}, nil)
		return err
	})
}

func TestMediaList(t *testing.T) {
	assertEndpoint(t, "GET", "/media", func(c *Client) error {
		_, err := c.Media.List(context.Background(), nil, nil)
		return err
	})
}

func TestMediaGet(t *testing.T) {
	assertEndpoint(t, "GET", "/media/test-mediaId", func(c *Client) error {
		_, err := c.Media.Get(context.Background(), "test-mediaId", nil)
		return err
	})
}

func TestMediaDelete(t *testing.T) {
	assertEndpoint(t, "DELETE", "/media/test-mediaId", func(c *Client) error {
		_, err := c.Media.Delete(context.Background(), "test-mediaId", nil)
		return err
	})
}

func TestMediaGetUploadUrl(t *testing.T) {
	assertEndpoint(t, "POST", "/media/upload-url", func(c *Client) error {
		_, err := c.Media.GetUploadUrl(context.Background(), map[string]any{}, nil)
		return err
	})
}

func TestPresentationsGenerate(t *testing.T) {
	assertEndpoint(t, "POST", "/presentations/generate", func(c *Client) error {
		_, err := c.Presentations.Generate(context.Background(), map[string]any{}, nil)
		return err
	})
}

func TestPresentationsList(t *testing.T) {
	assertEndpoint(t, "GET", "/presentations", func(c *Client) error {
		_, err := c.Presentations.List(context.Background(), nil, nil)
		return err
	})
}

func TestPresentationsGet(t *testing.T) {
	assertEndpoint(t, "GET", "/presentations/test-presentationId", func(c *Client) error {
		_, err := c.Presentations.Get(context.Background(), "test-presentationId", nil)
		return err
	})
}

func TestPresentationsDelete(t *testing.T) {
	assertEndpoint(t, "DELETE", "/presentations/test-presentationId", func(c *Client) error {
		_, err := c.Presentations.Delete(context.Background(), "test-presentationId", nil)
		return err
	})
}

func TestProfilesList(t *testing.T) {
	assertEndpoint(t, "GET", "/profiles", func(c *Client) error {
		_, err := c.Profiles.List(context.Background(), nil, nil)
		return err
	})
}

func TestProfilesCreate(t *testing.T) {
	assertEndpoint(t, "POST", "/profiles", func(c *Client) error {
		_, err := c.Profiles.Create(context.Background(), map[string]any{}, nil)
		return err
	})
}

func TestProfilesGet(t *testing.T) {
	assertEndpoint(t, "GET", "/profiles/test-id", func(c *Client) error {
		_, err := c.Profiles.Get(context.Background(), "test-id", nil)
		return err
	})
}

func TestProfilesDelete(t *testing.T) {
	assertEndpoint(t, "DELETE", "/profiles/test-id", func(c *Client) error {
		_, err := c.Profiles.Delete(context.Background(), "test-id", map[string]any{}, nil)
		return err
	})
}

func TestProfilesListAccounts(t *testing.T) {
	assertEndpoint(t, "GET", "/profiles/test-id/accounts", func(c *Client) error {
		_, err := c.Profiles.ListAccounts(context.Background(), "test-id", nil)
		return err
	})
}

func TestProfilesPause(t *testing.T) {
	assertEndpoint(t, "POST", "/profiles/test-id/pause", func(c *Client) error {
		_, err := c.Profiles.Pause(context.Background(), "test-id", nil)
		return err
	})
}

func TestProfilesResume(t *testing.T) {
	assertEndpoint(t, "POST", "/profiles/test-id/resume", func(c *Client) error {
		_, err := c.Profiles.Resume(context.Background(), "test-id", nil)
		return err
	})
}

func TestProfilesCreateConnectLink(t *testing.T) {
	assertEndpoint(t, "POST", "/profiles/test-id/connect-link", func(c *Client) error {
		_, err := c.Profiles.CreateConnectLink(context.Background(), "test-id", map[string]any{}, nil)
		return err
	})
}

func TestProfilesCreateConnectUrl(t *testing.T) {
	assertEndpoint(t, "POST", "/profiles/test-id/connect/test-platform", func(c *Client) error {
		_, err := c.Profiles.CreateConnectUrl(context.Background(), "test-id", "test-platform", map[string]any{}, nil)
		return err
	})
}

func TestProfilesGetAccountBilling(t *testing.T) {
	assertEndpoint(t, "GET", "/me/account-billing", func(c *Client) error {
		_, err := c.Profiles.GetAccountBilling(context.Background(), nil)
		return err
	})
}

func TestReviewsList(t *testing.T) {
	assertEndpoint(t, "GET", "/reviews", func(c *Client) error {
		_, err := c.Reviews.List(context.Background(), nil, nil)
		return err
	})
}

func TestReviewsReplyTo(t *testing.T) {
	assertEndpoint(t, "POST", "/reviews/test-reviewId/reply", func(c *Client) error {
		_, err := c.Reviews.ReplyTo(context.Background(), "test-reviewId", map[string]any{}, nil)
		return err
	})
}

func TestReviewsDeleteReply(t *testing.T) {
	assertEndpoint(t, "DELETE", "/reviews/test-reviewId/reply", func(c *Client) error {
		_, err := c.Reviews.DeleteReply(context.Background(), "test-reviewId", nil)
		return err
	})
}

func TestReviewsSync(t *testing.T) {
	assertEndpoint(t, "POST", "/reviews/sync", func(c *Client) error {
		_, err := c.Reviews.Sync(context.Background(), map[string]any{}, nil)
		return err
	})
}

func TestSEOKeywordResearch(t *testing.T) {
	assertEndpoint(t, "POST", "/seo/keyword-research", func(c *Client) error {
		_, err := c.SEO.KeywordResearch(context.Background(), map[string]any{}, nil)
		return err
	})
}

func TestSEOSerp(t *testing.T) {
	assertEndpoint(t, "POST", "/seo/serp", func(c *Client) error {
		_, err := c.SEO.Serp(context.Background(), map[string]any{}, nil)
		return err
	})
}

func TestSEOKeywordDifficulty(t *testing.T) {
	assertEndpoint(t, "POST", "/seo/keyword-difficulty", func(c *Client) error {
		_, err := c.SEO.KeywordDifficulty(context.Background(), map[string]any{}, nil)
		return err
	})
}

func TestSEORankedKeywords(t *testing.T) {
	assertEndpoint(t, "POST", "/seo/ranked-keywords", func(c *Client) error {
		_, err := c.SEO.RankedKeywords(context.Background(), map[string]any{}, nil)
		return err
	})
}

func TestSEODomainOverview(t *testing.T) {
	assertEndpoint(t, "POST", "/seo/domain-overview", func(c *Client) error {
		_, err := c.SEO.DomainOverview(context.Background(), map[string]any{}, nil)
		return err
	})
}

func TestSEOCompetitors(t *testing.T) {
	assertEndpoint(t, "POST", "/seo/competitors", func(c *Client) error {
		_, err := c.SEO.Competitors(context.Background(), map[string]any{}, nil)
		return err
	})
}

func TestSEOBacklinksSummary(t *testing.T) {
	assertEndpoint(t, "POST", "/seo/backlinks-summary", func(c *Client) error {
		_, err := c.SEO.BacklinksSummary(context.Background(), map[string]any{}, nil)
		return err
	})
}

func TestSEOAudit(t *testing.T) {
	assertEndpoint(t, "POST", "/seo/audit", func(c *Client) error {
		_, err := c.SEO.Audit(context.Background(), map[string]any{}, nil)
		return err
	})
}

func TestSEOBacklinkProspects(t *testing.T) {
	assertEndpoint(t, "POST", "/seo/backlink-prospects", func(c *Client) error {
		_, err := c.SEO.BacklinkProspects(context.Background(), map[string]any{}, nil)
		return err
	})
}

func TestSEOReferringDomains(t *testing.T) {
	assertEndpoint(t, "POST", "/seo/referring-domains", func(c *Client) error {
		_, err := c.SEO.ReferringDomains(context.Background(), map[string]any{}, nil)
		return err
	})
}

func TestSEOBacklinkAnchors(t *testing.T) {
	assertEndpoint(t, "POST", "/seo/backlink-anchors", func(c *Client) error {
		_, err := c.SEO.BacklinkAnchors(context.Background(), map[string]any{}, nil)
		return err
	})
}

func TestSEOSpamScore(t *testing.T) {
	assertEndpoint(t, "POST", "/seo/spam-score", func(c *Client) error {
		_, err := c.SEO.SpamScore(context.Background(), map[string]any{}, nil)
		return err
	})
}

func TestSEORankHistory(t *testing.T) {
	assertEndpoint(t, "POST", "/seo/rank-history", func(c *Client) error {
		_, err := c.SEO.RankHistory(context.Background(), map[string]any{}, nil)
		return err
	})
}

func TestSEOSiteAudit(t *testing.T) {
	assertEndpoint(t, "POST", "/seo/site-audit", func(c *Client) error {
		_, err := c.SEO.SiteAudit(context.Background(), map[string]any{}, nil)
		return err
	})
}

func TestSEOBrandLookup(t *testing.T) {
	assertEndpoint(t, "POST", "/seo/brand-lookup", func(c *Client) error {
		_, err := c.SEO.BrandLookup(context.Background(), map[string]any{}, nil)
		return err
	})
}

func TestSEOPromptExplorer(t *testing.T) {
	assertEndpoint(t, "POST", "/seo/prompt-explorer", func(c *Client) error {
		_, err := c.SEO.PromptExplorer(context.Background(), map[string]any{}, nil)
		return err
	})
}

func TestSEOAiAudit(t *testing.T) {
	assertEndpoint(t, "POST", "/seo/ai-audit", func(c *Client) error {
		_, err := c.SEO.AiAudit(context.Background(), map[string]any{}, nil)
		return err
	})
}

func TestShortsGenerate(t *testing.T) {
	assertEndpoint(t, "POST", "/shorts/generate", func(c *Client) error {
		_, err := c.Shorts.Generate(context.Background(), map[string]any{}, nil)
		return err
	})
}

func TestShortsList(t *testing.T) {
	assertEndpoint(t, "GET", "/shorts", func(c *Client) error {
		_, err := c.Shorts.List(context.Background(), nil, nil)
		return err
	})
}

func TestShortsGet(t *testing.T) {
	assertEndpoint(t, "GET", "/shorts/test-uid", func(c *Client) error {
		_, err := c.Shorts.Get(context.Background(), "test-uid", nil)
		return err
	})
}

func TestSocialListAccounts(t *testing.T) {
	assertEndpoint(t, "GET", "/social/accounts", func(c *Client) error {
		_, err := c.Social.ListAccounts(context.Background(), nil)
		return err
	})
}

func TestSocialListPosts(t *testing.T) {
	assertEndpoint(t, "GET", "/social/posts", func(c *Client) error {
		_, err := c.Social.ListPosts(context.Background(), nil, nil)
		return err
	})
}

func TestSocialCreatePost(t *testing.T) {
	assertEndpoint(t, "POST", "/social/posts", func(c *Client) error {
		_, err := c.Social.CreatePost(context.Background(), map[string]any{}, nil)
		return err
	})
}

func TestSocialSchedulePost(t *testing.T) {
	assertEndpoint(t, "POST", "/social/posts/schedule", func(c *Client) error {
		_, err := c.Social.SchedulePost(context.Background(), map[string]any{}, nil)
		return err
	})
}

func TestSocialGetPost(t *testing.T) {
	assertEndpoint(t, "GET", "/social/posts/test-postId", func(c *Client) error {
		_, err := c.Social.GetPost(context.Background(), "test-postId", nil)
		return err
	})
}

func TestSocialUpdatePost(t *testing.T) {
	assertEndpoint(t, "PATCH", "/social/posts/test-postId", func(c *Client) error {
		_, err := c.Social.UpdatePost(context.Background(), "test-postId", map[string]any{}, nil)
		return err
	})
}

func TestSocialDeletePost(t *testing.T) {
	assertEndpoint(t, "DELETE", "/social/posts/test-postId", func(c *Client) error {
		_, err := c.Social.DeletePost(context.Background(), "test-postId", nil)
		return err
	})
}

func TestSocialUpdateAccount(t *testing.T) {
	assertEndpoint(t, "PATCH", "/social/accounts/test-accountId", func(c *Client) error {
		_, err := c.Social.UpdateAccount(context.Background(), "test-accountId", map[string]any{}, nil)
		return err
	})
}

func TestSocialDisconnectAccount(t *testing.T) {
	assertEndpoint(t, "DELETE", "/social/accounts/test-accountId", func(c *Client) error {
		_, err := c.Social.DisconnectAccount(context.Background(), "test-accountId", nil)
		return err
	})
}

func TestSocialGetAccountHealth(t *testing.T) {
	assertEndpoint(t, "GET", "/social/accounts/test-accountId/health", func(c *Client) error {
		_, err := c.Social.GetAccountHealth(context.Background(), "test-accountId", nil)
		return err
	})
}

func TestSocialGetAccountReconnectUrl(t *testing.T) {
	assertEndpoint(t, "GET", "/social/accounts/test-accountId/reconnect-url", func(c *Client) error {
		_, err := c.Social.GetAccountReconnectUrl(context.Background(), "test-accountId", nil)
		return err
	})
}

func TestSocialPauseAccount(t *testing.T) {
	assertEndpoint(t, "POST", "/social/accounts/test-accountId/pause", func(c *Client) error {
		_, err := c.Social.PauseAccount(context.Background(), "test-accountId", nil)
		return err
	})
}

func TestSocialResumeAccount(t *testing.T) {
	assertEndpoint(t, "POST", "/social/accounts/test-accountId/resume", func(c *Client) error {
		_, err := c.Social.ResumeAccount(context.Background(), "test-accountId", nil)
		return err
	})
}

func TestSocialRetryPost(t *testing.T) {
	assertEndpoint(t, "POST", "/social/posts/test-postId/retry", func(c *Client) error {
		_, err := c.Social.RetryPost(context.Background(), "test-postId", map[string]any{}, nil)
		return err
	})
}

func TestSocialConnectAccountStatus(t *testing.T) {
	assertEndpoint(t, "GET", "/social/connect/test-platform", func(c *Client) error {
		_, err := c.Social.ConnectAccountStatus(context.Background(), "test-platform", nil)
		return err
	})
}

func TestSocialConnectAccount(t *testing.T) {
	assertEndpoint(t, "POST", "/social/connect/test-platform", func(c *Client) error {
		_, err := c.Social.ConnectAccount(context.Background(), "test-platform", map[string]any{}, nil)
		return err
	})
}

func TestSocialListQueues(t *testing.T) {
	assertEndpoint(t, "GET", "/social/queues", func(c *Client) error {
		_, err := c.Social.ListQueues(context.Background(), nil)
		return err
	})
}

func TestSocialCreateQueue(t *testing.T) {
	assertEndpoint(t, "POST", "/social/queues", func(c *Client) error {
		_, err := c.Social.CreateQueue(context.Background(), map[string]any{}, nil)
		return err
	})
}

func TestSocialGetQueue(t *testing.T) {
	assertEndpoint(t, "GET", "/social/queues/test-queueId", func(c *Client) error {
		_, err := c.Social.GetQueue(context.Background(), "test-queueId", nil)
		return err
	})
}

func TestSocialUpdateQueue(t *testing.T) {
	assertEndpoint(t, "PUT", "/social/queues/test-queueId", func(c *Client) error {
		_, err := c.Social.UpdateQueue(context.Background(), "test-queueId", map[string]any{}, nil)
		return err
	})
}

func TestSocialDeleteQueue(t *testing.T) {
	assertEndpoint(t, "DELETE", "/social/queues/test-queueId", func(c *Client) error {
		_, err := c.Social.DeleteQueue(context.Background(), "test-queueId", nil)
		return err
	})
}

func TestSocialGetQueueNextSlot(t *testing.T) {
	assertEndpoint(t, "GET", "/social/queues/test-queueId/next-slot", func(c *Client) error {
		_, err := c.Social.GetQueueNextSlot(context.Background(), "test-queueId", nil)
		return err
	})
}

func TestSocialPreviewQueueSlots(t *testing.T) {
	assertEndpoint(t, "GET", "/social/queues/test-queueId/preview", func(c *Client) error {
		_, err := c.Social.PreviewQueueSlots(context.Background(), "test-queueId", nil, nil)
		return err
	})
}

func TestSocialUnpublishPost(t *testing.T) {
	assertEndpoint(t, "POST", "/social/posts/test-postId/unpublish", func(c *Client) error {
		_, err := c.Social.UnpublishPost(context.Background(), "test-postId", map[string]any{}, nil)
		return err
	})
}

func TestSocialValidatePost(t *testing.T) {
	assertEndpoint(t, "POST", "/social/validate/post", func(c *Client) error {
		_, err := c.Social.ValidatePost(context.Background(), map[string]any{}, nil)
		return err
	})
}

func TestSocialValidateMedia(t *testing.T) {
	assertEndpoint(t, "POST", "/social/validate/media", func(c *Client) error {
		_, err := c.Social.ValidateMedia(context.Background(), map[string]any{}, nil)
		return err
	})
}

func TestSocialStopPostRecycle(t *testing.T) {
	assertEndpoint(t, "DELETE", "/social/posts/test-postId/recycle", func(c *Client) error {
		_, err := c.Social.StopPostRecycle(context.Background(), "test-postId", nil)
		return err
	})
}

func TestSocialBulkSchedulePosts(t *testing.T) {
	assertEndpoint(t, "POST", "/social/posts/bulk", func(c *Client) error {
		_, err := c.Social.BulkSchedulePosts(context.Background(), map[string]any{}, nil)
		return err
	})
}

func TestSocialValidateBulkBatch(t *testing.T) {
	assertEndpoint(t, "POST", "/social/posts/bulk/validate", func(c *Client) error {
		_, err := c.Social.ValidateBulkBatch(context.Background(), map[string]any{}, nil)
		return err
	})
}

func TestSocialBulkAccountHealth(t *testing.T) {
	assertEndpoint(t, "GET", "/social/accounts/health", func(c *Client) error {
		_, err := c.Social.BulkAccountHealth(context.Background(), nil)
		return err
	})
}

func TestSocialAccountFollowerStats(t *testing.T) {
	assertEndpoint(t, "GET", "/social/accounts/follower-stats", func(c *Client) error {
		_, err := c.Social.AccountFollowerStats(context.Background(), nil, nil)
		return err
	})
}

func TestSocialTiktokCreatorInfo(t *testing.T) {
	assertEndpoint(t, "GET", "/social/accounts/test-accountId/tiktok/creator-info", func(c *Client) error {
		_, err := c.Social.TiktokCreatorInfo(context.Background(), "test-accountId", nil)
		return err
	})
}

func TestSocialMoveAccount(t *testing.T) {
	assertEndpoint(t, "POST", "/social/accounts/test-accountId/move", func(c *Client) error {
		_, err := c.Social.MoveAccount(context.Background(), "test-accountId", map[string]any{}, nil)
		return err
	})
}

func TestSocialListAccountGroups(t *testing.T) {
	assertEndpoint(t, "GET", "/social/account-groups", func(c *Client) error {
		_, err := c.Social.ListAccountGroups(context.Background(), nil)
		return err
	})
}

func TestSocialCreateAccountGroup(t *testing.T) {
	assertEndpoint(t, "POST", "/social/account-groups", func(c *Client) error {
		_, err := c.Social.CreateAccountGroup(context.Background(), map[string]any{}, nil)
		return err
	})
}

func TestSocialGetAccountGroup(t *testing.T) {
	assertEndpoint(t, "GET", "/social/account-groups/test-groupId", func(c *Client) error {
		_, err := c.Social.GetAccountGroup(context.Background(), "test-groupId", nil)
		return err
	})
}

func TestSocialUpdateAccountGroup(t *testing.T) {
	assertEndpoint(t, "PUT", "/social/account-groups/test-groupId", func(c *Client) error {
		_, err := c.Social.UpdateAccountGroup(context.Background(), "test-groupId", map[string]any{}, nil)
		return err
	})
}

func TestSocialDeleteAccountGroup(t *testing.T) {
	assertEndpoint(t, "DELETE", "/social/account-groups/test-groupId", func(c *Client) error {
		_, err := c.Social.DeleteAccountGroup(context.Background(), "test-groupId", nil)
		return err
	})
}

func TestSocialGetConversation(t *testing.T) {
	assertEndpoint(t, "GET", "/social/conversations/test-conversationId", func(c *Client) error {
		_, err := c.Social.GetConversation(context.Background(), "test-conversationId", nil)
		return err
	})
}

func TestSocialUpdateConversation(t *testing.T) {
	assertEndpoint(t, "PATCH", "/social/conversations/test-conversationId", func(c *Client) error {
		_, err := c.Social.UpdateConversation(context.Background(), "test-conversationId", map[string]any{}, nil)
		return err
	})
}

func TestSocialSearchConversations(t *testing.T) {
	assertEndpoint(t, "GET", "/social/conversations/search", func(c *Client) error {
		_, err := c.Social.SearchConversations(context.Background(), nil, nil)
		return err
	})
}

func TestSocialPinterestBoards(t *testing.T) {
	assertEndpoint(t, "GET", "/social/accounts/test-accountId/pinterest/boards", func(c *Client) error {
		_, err := c.Social.PinterestBoards(context.Background(), "test-accountId", nil)
		return err
	})
}

func TestSocialYoutubePlaylists(t *testing.T) {
	assertEndpoint(t, "GET", "/social/accounts/test-accountId/youtube/playlists", func(c *Client) error {
		_, err := c.Social.YoutubePlaylists(context.Background(), "test-accountId", nil)
		return err
	})
}

func TestSocialInstagramPublishingLimit(t *testing.T) {
	assertEndpoint(t, "GET", "/social/accounts/test-accountId/instagram/publishing-limit", func(c *Client) error {
		_, err := c.Social.InstagramPublishingLimit(context.Background(), "test-accountId", nil)
		return err
	})
}

func TestSocialGmbPerformance(t *testing.T) {
	assertEndpoint(t, "GET", "/social/accounts/test-accountId/gmb/performance", func(c *Client) error {
		_, err := c.Social.GmbPerformance(context.Background(), "test-accountId", nil, nil)
		return err
	})
}

func TestSocialGmbSearchKeywords(t *testing.T) {
	assertEndpoint(t, "GET", "/social/accounts/test-accountId/gmb/search-keywords", func(c *Client) error {
		_, err := c.Social.GmbSearchKeywords(context.Background(), "test-accountId", nil, nil)
		return err
	})
}

func TestSocialRedditSearch(t *testing.T) {
	assertEndpoint(t, "GET", "/social/accounts/test-accountId/reddit/search", func(c *Client) error {
		_, err := c.Social.RedditSearch(context.Background(), "test-accountId", nil, nil)
		return err
	})
}

func TestSocialRedditFeed(t *testing.T) {
	assertEndpoint(t, "GET", "/social/accounts/test-accountId/reddit/feed", func(c *Client) error {
		_, err := c.Social.RedditFeed(context.Background(), "test-accountId", nil, nil)
		return err
	})
}

func TestSocialRedditSubreddits(t *testing.T) {
	assertEndpoint(t, "GET", "/social/accounts/test-accountId/reddit/subreddits", func(c *Client) error {
		_, err := c.Social.RedditSubreddits(context.Background(), "test-accountId", nil)
		return err
	})
}

func TestSocialRedditSubredditRules(t *testing.T) {
	assertEndpoint(t, "GET", "/social/accounts/test-accountId/reddit/subreddits/test-subreddit/rules", func(c *Client) error {
		_, err := c.Social.RedditSubredditRules(context.Background(), "test-accountId", "test-subreddit", nil)
		return err
	})
}

func TestSocialInstagramStories(t *testing.T) {
	assertEndpoint(t, "GET", "/social/accounts/test-accountId/instagram/stories", func(c *Client) error {
		_, err := c.Social.InstagramStories(context.Background(), "test-accountId", nil)
		return err
	})
}

func TestSocialFacebookPostReactions(t *testing.T) {
	assertEndpoint(t, "GET", "/social/accounts/test-accountId/facebook/post-reactions", func(c *Client) error {
		_, err := c.Social.FacebookPostReactions(context.Background(), "test-accountId", nil, nil)
		return err
	})
}

func TestSocialInstagramStoryInsights(t *testing.T) {
	assertEndpoint(t, "GET", "/social/accounts/test-accountId/instagram/stories/test-storyId/insights", func(c *Client) error {
		_, err := c.Social.InstagramStoryInsights(context.Background(), "test-accountId", "test-storyId", nil, nil)
		return err
	})
}

func TestSocialXRetweet(t *testing.T) {
	assertEndpoint(t, "POST", "/social/accounts/test-accountId/x/retweets", func(c *Client) error {
		_, err := c.Social.XRetweet(context.Background(), "test-accountId", map[string]any{}, nil)
		return err
	})
}

func TestSocialXUnretweet(t *testing.T) {
	assertEndpoint(t, "DELETE", "/social/accounts/test-accountId/x/retweets/test-tweetId", func(c *Client) error {
		_, err := c.Social.XUnretweet(context.Background(), "test-accountId", "test-tweetId", nil)
		return err
	})
}

func TestURLsShorten(t *testing.T) {
	assertEndpoint(t, "POST", "/urls/shorten", func(c *Client) error {
		_, err := c.URLs.Shorten(context.Background(), map[string]any{}, nil)
		return err
	})
}

func TestURLsList(t *testing.T) {
	assertEndpoint(t, "GET", "/urls", func(c *Client) error {
		_, err := c.URLs.List(context.Background(), nil, nil)
		return err
	})
}

func TestURLsGet(t *testing.T) {
	assertEndpoint(t, "GET", "/urls/test-urlId", func(c *Client) error {
		_, err := c.URLs.Get(context.Background(), "test-urlId", nil)
		return err
	})
}

func TestURLsDelete(t *testing.T) {
	assertEndpoint(t, "DELETE", "/urls/test-urlId", func(c *Client) error {
		_, err := c.URLs.Delete(context.Background(), "test-urlId", nil)
		return err
	})
}

func TestURLsGetStats(t *testing.T) {
	assertEndpoint(t, "GET", "/urls/test-urlId/stats", func(c *Client) error {
		_, err := c.URLs.GetStats(context.Background(), "test-urlId", nil)
		return err
	})
}

func TestVideosListModels(t *testing.T) {
	assertEndpoint(t, "GET", "/videos/models", func(c *Client) error {
		_, err := c.Videos.ListModels(context.Background(), nil)
		return err
	})
}

func TestVideosGenerate(t *testing.T) {
	assertEndpoint(t, "POST", "/videos/generate", func(c *Client) error {
		_, err := c.Videos.Generate(context.Background(), map[string]any{}, nil)
		return err
	})
}

func TestVideosList(t *testing.T) {
	assertEndpoint(t, "GET", "/videos", func(c *Client) error {
		_, err := c.Videos.List(context.Background(), nil, nil)
		return err
	})
}

func TestVideosGet(t *testing.T) {
	assertEndpoint(t, "GET", "/videos/test-videoId", func(c *Client) error {
		_, err := c.Videos.Get(context.Background(), "test-videoId", nil)
		return err
	})
}

func TestVideosDelete(t *testing.T) {
	assertEndpoint(t, "DELETE", "/videos/test-videoId", func(c *Client) error {
		_, err := c.Videos.Delete(context.Background(), "test-videoId", nil)
		return err
	})
}

func TestVideosGenerateHook(t *testing.T) {
	assertEndpoint(t, "POST", "/videos/hook", func(c *Client) error {
		_, err := c.Videos.GenerateHook(context.Background(), map[string]any{}, nil)
		return err
	})
}

func TestVideosSuggestBroll(t *testing.T) {
	assertEndpoint(t, "POST", "/videos/broll-suggest", func(c *Client) error {
		_, err := c.Videos.SuggestBroll(context.Background(), map[string]any{}, nil)
		return err
	})
}

func TestVideosSuggestEmphasis(t *testing.T) {
	assertEndpoint(t, "POST", "/videos/emphasis", func(c *Client) error {
		_, err := c.Videos.SuggestEmphasis(context.Background(), map[string]any{}, nil)
		return err
	})
}

func TestVideosGenerateViralThumbnail(t *testing.T) {
	assertEndpoint(t, "POST", "/videos/viral-thumbnail", func(c *Client) error {
		_, err := c.Videos.GenerateViralThumbnail(context.Background(), map[string]any{}, nil)
		return err
	})
}

func TestWebhooksList(t *testing.T) {
	assertEndpoint(t, "GET", "/webhooks", func(c *Client) error {
		_, err := c.Webhooks.List(context.Background(), nil)
		return err
	})
}

func TestWebhooksCreate(t *testing.T) {
	assertEndpoint(t, "POST", "/webhooks", func(c *Client) error {
		_, err := c.Webhooks.Create(context.Background(), map[string]any{}, nil)
		return err
	})
}

func TestWebhooksUpdate(t *testing.T) {
	assertEndpoint(t, "PUT", "/webhooks/test-id", func(c *Client) error {
		_, err := c.Webhooks.Update(context.Background(), "test-id", map[string]any{}, nil)
		return err
	})
}

func TestWebhooksDelete(t *testing.T) {
	assertEndpoint(t, "DELETE", "/webhooks/test-id", func(c *Client) error {
		_, err := c.Webhooks.Delete(context.Background(), "test-id", nil)
		return err
	})
}

func TestWebhooksListLogs(t *testing.T) {
	assertEndpoint(t, "GET", "/webhooks/logs", func(c *Client) error {
		_, err := c.Webhooks.ListLogs(context.Background(), nil, nil)
		return err
	})
}

func TestWebhooksTest(t *testing.T) {
	assertEndpoint(t, "POST", "/webhooks/test-id/test", func(c *Client) error {
		_, err := c.Webhooks.Test(context.Background(), "test-id", nil)
		return err
	})
}

func TestWorkspacesList(t *testing.T) {
	assertEndpoint(t, "GET", "/workspaces", func(c *Client) error {
		_, err := c.Workspaces.List(context.Background(), nil)
		return err
	})
}

func TestWorkspacesCreate(t *testing.T) {
	assertEndpoint(t, "POST", "/workspaces", func(c *Client) error {
		_, err := c.Workspaces.Create(context.Background(), map[string]any{}, nil)
		return err
	})
}

func TestWorkspacesBulkAction(t *testing.T) {
	assertEndpoint(t, "POST", "/workspaces/bulk", func(c *Client) error {
		_, err := c.Workspaces.BulkAction(context.Background(), map[string]any{}, nil)
		return err
	})
}

func TestWorkspacesGet(t *testing.T) {
	assertEndpoint(t, "GET", "/workspaces/test-id", func(c *Client) error {
		_, err := c.Workspaces.Get(context.Background(), "test-id", nil)
		return err
	})
}

func TestWorkspacesDelete(t *testing.T) {
	assertEndpoint(t, "DELETE", "/workspaces/test-id", func(c *Client) error {
		_, err := c.Workspaces.Delete(context.Background(), "test-id", map[string]any{}, nil)
		return err
	})
}

func TestWorkspacesDisableSaas(t *testing.T) {
	assertEndpoint(t, "POST", "/workspaces/test-id/disable-saas", func(c *Client) error {
		_, err := c.Workspaces.DisableSaas(context.Background(), "test-id", map[string]any{}, nil)
		return err
	})
}

func TestWorkspacesPause(t *testing.T) {
	assertEndpoint(t, "POST", "/workspaces/test-id/pause", func(c *Client) error {
		_, err := c.Workspaces.Pause(context.Background(), "test-id", nil)
		return err
	})
}

func TestWorkspacesResume(t *testing.T) {
	assertEndpoint(t, "POST", "/workspaces/test-id/resume", func(c *Client) error {
		_, err := c.Workspaces.Resume(context.Background(), "test-id", nil)
		return err
	})
}

func TestWorkspacesGetSubscription(t *testing.T) {
	assertEndpoint(t, "GET", "/workspaces/test-id/subscription", func(c *Client) error {
		_, err := c.Workspaces.GetSubscription(context.Background(), "test-id", nil)
		return err
	})
}

func TestWorkspacesGetWallet(t *testing.T) {
	assertEndpoint(t, "GET", "/workspaces/test-id/wallet", func(c *Client) error {
		_, err := c.Workspaces.GetWallet(context.Background(), "test-id", nil)
		return err
	})
}

func TestWorkspacesListSaasPlans(t *testing.T) {
	assertEndpoint(t, "GET", "/saas/plans", func(c *Client) error {
		_, err := c.Workspaces.ListSaasPlans(context.Background(), nil)
		return err
	})
}

func TestWorkspacesGetSaasPlan(t *testing.T) {
	assertEndpoint(t, "GET", "/saas/plans/test-id", func(c *Client) error {
		_, err := c.Workspaces.GetSaasPlan(context.Background(), "test-id", nil)
		return err
	})
}
