// Code generated by scripts/generate from openapi.json. DO NOT EDIT.

package smartlyq

import (
	"context"
	"net/url"
)

// resources holds one field per API resource group; it is embedded in Client.
type resources struct {
	Account       *AccountResource
	Captain       *CaptainResource
	Analytics     *AnalyticsResource
	Articles      *ArticlesResource
	Audio         *AudioResource
	Automations   *AutomationsResource
	Chatbots      *ChatbotsResource
	Comments      *CommentsResource
	Content       *ContentResource
	CRM           *CRMResource
	Contacts      *ContactsResource
	CustomFields  *CustomFieldsResource
	Opportunities *OpportunitiesResource
	Messages      *MessagesResource
	Images        *ImagesResource
	Jobs          *JobsResource
	Media         *MediaResource
	Presentations *PresentationsResource
	Profiles      *ProfilesResource
	Reviews       *ReviewsResource
	SEO           *SEOResource
	Shorts        *ShortsResource
	Social        *SocialResource
	URLs          *URLsResource
	Videos        *VideosResource
	Webhooks      *WebhooksResource
	Workspaces    *WorkspacesResource
}

func (c *Client) initResources() {
	c.Account = &AccountResource{client: c}
	c.Captain = &CaptainResource{client: c}
	c.Analytics = &AnalyticsResource{client: c}
	c.Articles = &ArticlesResource{client: c}
	c.Audio = &AudioResource{client: c}
	c.Automations = &AutomationsResource{client: c}
	c.Chatbots = &ChatbotsResource{client: c}
	c.Comments = &CommentsResource{client: c}
	c.Content = &ContentResource{client: c}
	c.CRM = &CRMResource{client: c}
	c.Contacts = &ContactsResource{client: c}
	c.CustomFields = &CustomFieldsResource{client: c}
	c.Opportunities = &OpportunitiesResource{client: c}
	c.Messages = &MessagesResource{client: c}
	c.Images = &ImagesResource{client: c}
	c.Jobs = &JobsResource{client: c}
	c.Media = &MediaResource{client: c}
	c.Presentations = &PresentationsResource{client: c}
	c.Profiles = &ProfilesResource{client: c}
	c.Reviews = &ReviewsResource{client: c}
	c.SEO = &SEOResource{client: c}
	c.Shorts = &ShortsResource{client: c}
	c.Social = &SocialResource{client: c}
	c.URLs = &URLsResource{client: c}
	c.Videos = &VideosResource{client: c}
	c.Webhooks = &WebhooksResource{client: c}
	c.Workspaces = &WorkspacesResource{client: c}
}

// AccountResource groups the Account endpoints.
type AccountResource struct{ client *Client }

// GetMe - Get current user profile.
//
// GET /me
func (r *AccountResource) GetMe(ctx context.Context, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "GET", "/me", nil, nil, opts)
}

// GetMeUsage - Get usage summary.
//
// GET /me/usage
func (r *AccountResource) GetMeUsage(ctx context.Context, query map[string]string, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "GET", "/me/usage", query, nil, opts)
}

// GetMeBalance - Get wallet balance.
//
// GET /me/balance
func (r *AccountResource) GetMeBalance(ctx context.Context, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "GET", "/me/balance", nil, nil, opts)
}

// CaptainResource groups the AI Captain endpoints.
type CaptainResource struct{ client *Client }

// SendMessage - Send AI Captain message.
//
// POST /captain/messages
func (r *CaptainResource) SendMessage(ctx context.Context, body map[string]any, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "POST", "/captain/messages", nil, body, opts)
}

// ListConversations - List AI Captain conversations.
//
// GET /captain/conversations
func (r *CaptainResource) ListConversations(ctx context.Context, query map[string]string, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "GET", "/captain/conversations", query, nil, opts)
}

// GetConversation - Get AI Captain conversation.
//
// GET /captain/conversations/{conversation_id}
func (r *CaptainResource) GetConversation(ctx context.Context, conversationId string, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "GET", "/captain/conversations/"+url.PathEscape(conversationId), nil, nil, opts)
}

// AnalyticsResource groups the Analytics endpoints.
type AnalyticsResource struct{ client *Client }

// GetOverview - Get analytics overview.
//
// GET /analytics/overview
func (r *AnalyticsResource) GetOverview(ctx context.Context, query map[string]string, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "GET", "/analytics/overview", query, nil, opts)
}

// GetPosts - Get post analytics.
//
// GET /analytics/posts
func (r *AnalyticsResource) GetPosts(ctx context.Context, query map[string]string, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "GET", "/analytics/posts", query, nil, opts)
}

// GetAccount - Get account analytics.
//
// GET /analytics/accounts/{account_id}
func (r *AnalyticsResource) GetAccount(ctx context.Context, accountId string, query map[string]string, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "GET", "/analytics/accounts/"+url.PathEscape(accountId), query, nil, opts)
}

// DailyMetrics - Daily metrics.
//
// GET /analytics/daily-metrics
func (r *AnalyticsResource) DailyMetrics(ctx context.Context, query map[string]string, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "GET", "/analytics/daily-metrics", query, nil, opts)
}

// BestTime - Best time to post.
//
// GET /analytics/best-time
func (r *AnalyticsResource) BestTime(ctx context.Context, query map[string]string, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "GET", "/analytics/best-time", query, nil, opts)
}

// ContentDecay - Content decay.
//
// GET /analytics/content-decay
func (r *AnalyticsResource) ContentDecay(ctx context.Context, query map[string]string, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "GET", "/analytics/content-decay", query, nil, opts)
}

// PostingFrequency - Posting frequency vs engagement.
//
// GET /analytics/posting-frequency
func (r *AnalyticsResource) PostingFrequency(ctx context.Context, query map[string]string, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "GET", "/analytics/posting-frequency", query, nil, opts)
}

// PostTimeline - Post metric timeline.
//
// GET /analytics/posts/{post_id}/timeline
func (r *AnalyticsResource) PostTimeline(ctx context.Context, postId string, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "GET", "/analytics/posts/"+url.PathEscape(postId)+"/timeline", nil, nil, opts)
}

// InboxVolume - Inbox volume.
//
// GET /analytics/inbox/volume
func (r *AnalyticsResource) InboxVolume(ctx context.Context, query map[string]string, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "GET", "/analytics/inbox/volume", query, nil, opts)
}

// InboxHeatmap - Inbox heatmap.
//
// GET /analytics/inbox/heatmap
func (r *AnalyticsResource) InboxHeatmap(ctx context.Context, query map[string]string, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "GET", "/analytics/inbox/heatmap", query, nil, opts)
}

// InboxSourceBreakdown - Inbox source breakdown.
//
// GET /analytics/inbox/source-breakdown
func (r *AnalyticsResource) InboxSourceBreakdown(ctx context.Context, query map[string]string, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "GET", "/analytics/inbox/source-breakdown", query, nil, opts)
}

// InboxResponseTime - Inbox response time.
//
// GET /analytics/inbox/response-time
func (r *AnalyticsResource) InboxResponseTime(ctx context.Context, query map[string]string, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "GET", "/analytics/inbox/response-time", query, nil, opts)
}

// InboxTopAccounts - Inbox top accounts.
//
// GET /analytics/inbox/top-accounts
func (r *AnalyticsResource) InboxTopAccounts(ctx context.Context, query map[string]string, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "GET", "/analytics/inbox/top-accounts", query, nil, opts)
}

// InboxConversations - Inbox conversation stats.
//
// GET /analytics/inbox/conversations
func (r *AnalyticsResource) InboxConversations(ctx context.Context, query map[string]string, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "GET", "/analytics/inbox/conversations", query, nil, opts)
}

// InboxConversationDetail - Conversation analytics.
//
// GET /analytics/inbox/conversations/{conversation_id}
func (r *AnalyticsResource) InboxConversationDetail(ctx context.Context, conversationId string, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "GET", "/analytics/inbox/conversations/"+url.PathEscape(conversationId), nil, nil, opts)
}

// ArticlesResource groups the Articles endpoints.
type ArticlesResource struct{ client *Client }

// Generate - Generate article.
//
// POST /articles/generate
func (r *ArticlesResource) Generate(ctx context.Context, body map[string]any, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "POST", "/articles/generate", nil, body, opts)
}

// List - List articles.
//
// GET /articles
func (r *ArticlesResource) List(ctx context.Context, query map[string]string, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "GET", "/articles", query, nil, opts)
}

// Get - Get article.
//
// GET /articles/{article_id}
func (r *ArticlesResource) Get(ctx context.Context, articleId string, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "GET", "/articles/"+url.PathEscape(articleId), nil, nil, opts)
}

// Delete - Delete article.
//
// DELETE /articles/{article_id}
func (r *ArticlesResource) Delete(ctx context.Context, articleId string, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "DELETE", "/articles/"+url.PathEscape(articleId), nil, nil, opts)
}

// AudioResource groups the Audio endpoints.
type AudioResource struct{ client *Client }

// TextToSpeech - Text to speech.
//
// POST /audio/text-to-speech
func (r *AudioResource) TextToSpeech(ctx context.Context, body map[string]any, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "POST", "/audio/text-to-speech", nil, body, opts)
}

// SpeechToText - Speech to text.
//
// POST /audio/speech-to-text
func (r *AudioResource) SpeechToText(ctx context.Context, body map[string]any, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "POST", "/audio/speech-to-text", nil, body, opts)
}

// Get - Get audio.
//
// GET /audio/{audio_id}
func (r *AudioResource) Get(ctx context.Context, audioId string, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "GET", "/audio/"+url.PathEscape(audioId), nil, nil, opts)
}

// AutomationsResource groups the Automations endpoints.
type AutomationsResource struct{ client *Client }

// List - List automations.
//
// GET /automations
func (r *AutomationsResource) List(ctx context.Context, query map[string]string, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "GET", "/automations", query, nil, opts)
}

// Get - Get automation.
//
// GET /automations/{automation_id}
func (r *AutomationsResource) Get(ctx context.Context, automationId string, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "GET", "/automations/"+url.PathEscape(automationId), nil, nil, opts)
}

// Activate - Activate automation.
//
// POST /automations/{automation_id}/activate
func (r *AutomationsResource) Activate(ctx context.Context, automationId string, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "POST", "/automations/"+url.PathEscape(automationId)+"/activate", nil, nil, opts)
}

// Deactivate - Pause automation.
//
// POST /automations/{automation_id}/deactivate
func (r *AutomationsResource) Deactivate(ctx context.Context, automationId string, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "POST", "/automations/"+url.PathEscape(automationId)+"/deactivate", nil, nil, opts)
}

// Trigger - Trigger automation.
//
// POST /automations/{automation_id}/trigger
func (r *AutomationsResource) Trigger(ctx context.Context, automationId string, body map[string]any, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "POST", "/automations/"+url.PathEscape(automationId)+"/trigger", nil, body, opts)
}

// ListRuns - List runs.
//
// GET /automations/{automation_id}/runs
func (r *AutomationsResource) ListRuns(ctx context.Context, automationId string, query map[string]string, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "GET", "/automations/"+url.PathEscape(automationId)+"/runs", query, nil, opts)
}

// GetRun - Get run.
//
// GET /automations/{automation_id}/runs/{run_id}
func (r *AutomationsResource) GetRun(ctx context.Context, automationId string, runId string, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "GET", "/automations/"+url.PathEscape(automationId)+"/runs/"+url.PathEscape(runId), nil, nil, opts)
}

// ChatbotsResource groups the Chatbot endpoints.
type ChatbotsResource struct{ client *Client }

// List - List chatbots.
//
// GET /chatbots
func (r *ChatbotsResource) List(ctx context.Context, query map[string]string, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "GET", "/chatbots", query, nil, opts)
}

// Create - Create chatbot.
//
// POST /chatbots
func (r *ChatbotsResource) Create(ctx context.Context, body map[string]any, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "POST", "/chatbots", nil, body, opts)
}

// Get - Get chatbot.
//
// GET /chatbots/{id}
func (r *ChatbotsResource) Get(ctx context.Context, id string, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "GET", "/chatbots/"+url.PathEscape(id), nil, nil, opts)
}

// Update - Update chatbot.
//
// PATCH /chatbots/{id}
func (r *ChatbotsResource) Update(ctx context.Context, id string, body map[string]any, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "PATCH", "/chatbots/"+url.PathEscape(id), nil, body, opts)
}

// Delete - Delete chatbot.
//
// DELETE /chatbots/{id}
func (r *ChatbotsResource) Delete(ctx context.Context, id string, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "DELETE", "/chatbots/"+url.PathEscape(id), nil, nil, opts)
}

// Train - Start chatbot training.
//
// POST /chatbots/{id}/train
func (r *ChatbotsResource) Train(ctx context.Context, id string, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "POST", "/chatbots/"+url.PathEscape(id)+"/train", nil, nil, opts)
}

// GetTrainStatus - Get chatbot training status.
//
// GET /chatbots/{id}/train-status
func (r *ChatbotsResource) GetTrainStatus(ctx context.Context, id string, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "GET", "/chatbots/"+url.PathEscape(id)+"/train-status", nil, nil, opts)
}

// SendMessage - Send chatbot message.
//
// POST /chatbots/{id}/messages
func (r *ChatbotsResource) SendMessage(ctx context.Context, id string, body map[string]any, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "POST", "/chatbots/"+url.PathEscape(id)+"/messages", nil, body, opts)
}

// ListConversations - List chatbot conversations.
//
// GET /chatbots/{id}/conversations
func (r *ChatbotsResource) ListConversations(ctx context.Context, id string, query map[string]string, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "GET", "/chatbots/"+url.PathEscape(id)+"/conversations", query, nil, opts)
}

// GetConversationMessages - Get conversation messages.
//
// GET /chatbots/{id}/conversations/{conv_id}/messages
func (r *ChatbotsResource) GetConversationMessages(ctx context.Context, id string, convId string, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "GET", "/chatbots/"+url.PathEscape(id)+"/conversations/"+url.PathEscape(convId)+"/messages", nil, nil, opts)
}

// CommentsResource groups the Comments endpoints.
type CommentsResource struct{ client *Client }

// List - List comments.
//
// GET /social/comments
func (r *CommentsResource) List(ctx context.Context, query map[string]string, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "GET", "/social/comments", query, nil, opts)
}

// ReplyTo - Reply to a comment.
//
// POST /social/comments/{comment_id}/reply
func (r *CommentsResource) ReplyTo(ctx context.Context, commentId string, body map[string]any, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "POST", "/social/comments/"+url.PathEscape(commentId)+"/reply", nil, body, opts)
}

// Hide - Hide or unhide a comment.
//
// POST /social/comments/{comment_id}/hide
func (r *CommentsResource) Hide(ctx context.Context, commentId string, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "POST", "/social/comments/"+url.PathEscape(commentId)+"/hide", nil, nil, opts)
}

// Delete - Delete a comment.
//
// DELETE /social/comments/{comment_id}
func (r *CommentsResource) Delete(ctx context.Context, commentId string, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "DELETE", "/social/comments/"+url.PathEscape(commentId), nil, nil, opts)
}

// ContentResource groups the Content endpoints.
type ContentResource struct{ client *Client }

// Rewrite - Rewrite content.
//
// POST /content/rewrite
func (r *ContentResource) Rewrite(ctx context.Context, body map[string]any, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "POST", "/content/rewrite", nil, body, opts)
}

// GenerateCaption - Generate a social caption.
//
// POST /content/caption
func (r *ContentResource) GenerateCaption(ctx context.Context, body map[string]any, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "POST", "/content/caption", nil, body, opts)
}

// CRMResource groups the CRM endpoints.
type CRMResource struct{ client *Client }

// DeleteContact - Delete contact.
//
// DELETE /contacts/{id}
func (r *CRMResource) DeleteContact(ctx context.Context, id string, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "DELETE", "/contacts/"+url.PathEscape(id), nil, nil, opts)
}

// UpdateCustomField - Update custom field.
//
// PATCH /custom-fields/{id}
func (r *CRMResource) UpdateCustomField(ctx context.Context, id string, body map[string]any, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "PATCH", "/custom-fields/"+url.PathEscape(id), nil, body, opts)
}

// BulkImportContacts - Bulk import contacts.
//
// POST /contacts/bulk
func (r *CRMResource) BulkImportContacts(ctx context.Context, body map[string]any, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "POST", "/contacts/bulk", nil, body, opts)
}

// ContactChannels - Contact channels.
//
// GET /contacts/{id}/channels
func (r *CRMResource) ContactChannels(ctx context.Context, id string, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "GET", "/contacts/"+url.PathEscape(id)+"/channels", nil, nil, opts)
}

// ContactsResource groups the CRM Contacts endpoints.
type ContactsResource struct{ client *Client }

// List - List contacts.
//
// GET /contacts
func (r *ContactsResource) List(ctx context.Context, query map[string]string, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "GET", "/contacts", query, nil, opts)
}

// Create - Create or upsert a contact.
//
// POST /contacts
func (r *ContactsResource) Create(ctx context.Context, body map[string]any, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "POST", "/contacts", nil, body, opts)
}

// Get - Get a contact.
//
// GET /contacts/{id}
func (r *ContactsResource) Get(ctx context.Context, id string, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "GET", "/contacts/"+url.PathEscape(id), nil, nil, opts)
}

// Update - Update a contact.
//
// PATCH /contacts/{id}
func (r *ContactsResource) Update(ctx context.Context, id string, body map[string]any, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "PATCH", "/contacts/"+url.PathEscape(id), nil, body, opts)
}

// AddTags - Add tags to a contact.
//
// POST /contacts/{id}/tags
func (r *ContactsResource) AddTags(ctx context.Context, id string, body map[string]any, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "POST", "/contacts/"+url.PathEscape(id)+"/tags", nil, body, opts)
}

// RemoveTags - Remove tags from a contact.
//
// DELETE /contacts/{id}/tags
func (r *ContactsResource) RemoveTags(ctx context.Context, id string, body map[string]any, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "DELETE", "/contacts/"+url.PathEscape(id)+"/tags", nil, body, opts)
}

// ListNotes - List contact notes.
//
// GET /contacts/{id}/notes
func (r *ContactsResource) ListNotes(ctx context.Context, id string, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "GET", "/contacts/"+url.PathEscape(id)+"/notes", nil, nil, opts)
}

// AddNote - Add a note to a contact.
//
// POST /contacts/{id}/notes
func (r *ContactsResource) AddNote(ctx context.Context, id string, body map[string]any, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "POST", "/contacts/"+url.PathEscape(id)+"/notes", nil, body, opts)
}

// Enroll - Enroll a contact in an automation.
//
// POST /contacts/{id}/enroll
func (r *ContactsResource) Enroll(ctx context.Context, id string, body map[string]any, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "POST", "/contacts/"+url.PathEscape(id)+"/enroll", nil, body, opts)
}

// AddMessage - Log a message on a contact's timeline.
//
// POST /contacts/{id}/messages
func (r *ContactsResource) AddMessage(ctx context.Context, id string, body map[string]any, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "POST", "/contacts/"+url.PathEscape(id)+"/messages", nil, body, opts)
}

// CustomFieldsResource groups the CRM Custom Fields endpoints.
type CustomFieldsResource struct{ client *Client }

// List - List custom fields.
//
// GET /custom-fields
func (r *CustomFieldsResource) List(ctx context.Context, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "GET", "/custom-fields", nil, nil, opts)
}

// Create - Create a custom field.
//
// POST /custom-fields
func (r *CustomFieldsResource) Create(ctx context.Context, body map[string]any, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "POST", "/custom-fields", nil, body, opts)
}

// Delete - Delete a custom field.
//
// DELETE /custom-fields/{id}
func (r *CustomFieldsResource) Delete(ctx context.Context, id string, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "DELETE", "/custom-fields/"+url.PathEscape(id), nil, nil, opts)
}

// OpportunitiesResource groups the CRM Opportunities endpoints.
type OpportunitiesResource struct{ client *Client }

// ListPipelines - List pipelines.
//
// GET /pipelines
func (r *OpportunitiesResource) ListPipelines(ctx context.Context, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "GET", "/pipelines", nil, nil, opts)
}

// CreatePipeline - Create a pipeline.
//
// POST /pipelines
func (r *OpportunitiesResource) CreatePipeline(ctx context.Context, body map[string]any, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "POST", "/pipelines", nil, body, opts)
}

// List - List opportunities.
//
// GET /opportunities
func (r *OpportunitiesResource) List(ctx context.Context, query map[string]string, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "GET", "/opportunities", query, nil, opts)
}

// Create - Create an opportunity.
//
// POST /opportunities
func (r *OpportunitiesResource) Create(ctx context.Context, body map[string]any, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "POST", "/opportunities", nil, body, opts)
}

// Get - Get an opportunity.
//
// GET /opportunities/{id}
func (r *OpportunitiesResource) Get(ctx context.Context, id string, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "GET", "/opportunities/"+url.PathEscape(id), nil, nil, opts)
}

// Update - Update an opportunity.
//
// PATCH /opportunities/{id}
func (r *OpportunitiesResource) Update(ctx context.Context, id string, body map[string]any, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "PATCH", "/opportunities/"+url.PathEscape(id), nil, body, opts)
}

// Delete - Delete an opportunity.
//
// DELETE /opportunities/{id}
func (r *OpportunitiesResource) Delete(ctx context.Context, id string, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "DELETE", "/opportunities/"+url.PathEscape(id), nil, nil, opts)
}

// UpdateStatus - Update opportunity status.
//
// POST /opportunities/{id}/status
func (r *OpportunitiesResource) UpdateStatus(ctx context.Context, id string, body map[string]any, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "POST", "/opportunities/"+url.PathEscape(id)+"/status", nil, body, opts)
}

// MessagesResource groups the Direct Messages endpoints.
type MessagesResource struct{ client *Client }

// ListConversations - List DM conversations.
//
// GET /social/conversations
func (r *MessagesResource) ListConversations(ctx context.Context, query map[string]string, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "GET", "/social/conversations", query, nil, opts)
}

// List - List messages in a conversation.
//
// GET /social/conversations/{conversation_id}/messages
func (r *MessagesResource) List(ctx context.Context, conversationId string, query map[string]string, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "GET", "/social/conversations/"+url.PathEscape(conversationId)+"/messages", query, nil, opts)
}

// Send - Send a direct message.
//
// POST /social/conversations/{conversation_id}/messages
func (r *MessagesResource) Send(ctx context.Context, conversationId string, body map[string]any, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "POST", "/social/conversations/"+url.PathEscape(conversationId)+"/messages", nil, body, opts)
}

// MarkConversationRead - Mark a conversation read.
//
// POST /social/conversations/{conversation_id}/read
func (r *MessagesResource) MarkConversationRead(ctx context.Context, conversationId string, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "POST", "/social/conversations/"+url.PathEscape(conversationId)+"/read", nil, nil, opts)
}

// ImagesResource groups the Images endpoints.
type ImagesResource struct{ client *Client }

// Generate - Generate image.
//
// POST /images/generate
func (r *ImagesResource) Generate(ctx context.Context, body map[string]any, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "POST", "/images/generate", nil, body, opts)
}

// List - List images.
//
// GET /images
func (r *ImagesResource) List(ctx context.Context, query map[string]string, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "GET", "/images", query, nil, opts)
}

// Get - Get image.
//
// GET /images/{image_id}
func (r *ImagesResource) Get(ctx context.Context, imageId string, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "GET", "/images/"+url.PathEscape(imageId), nil, nil, opts)
}

// Delete - Delete image.
//
// DELETE /images/{image_id}
func (r *ImagesResource) Delete(ctx context.Context, imageId string, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "DELETE", "/images/"+url.PathEscape(imageId), nil, nil, opts)
}

// JobsResource groups the Jobs endpoints.
type JobsResource struct{ client *Client }

// List - List jobs.
//
// GET /jobs
func (r *JobsResource) List(ctx context.Context, query map[string]string, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "GET", "/jobs", query, nil, opts)
}

// Get - Get job.
//
// GET /jobs/{job_id}
func (r *JobsResource) Get(ctx context.Context, jobId string, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "GET", "/jobs/"+url.PathEscape(jobId), nil, nil, opts)
}

// Cancel - Cancel job.
//
// POST /jobs/{job_id}/cancel
func (r *JobsResource) Cancel(ctx context.Context, jobId string, body map[string]any, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "POST", "/jobs/"+url.PathEscape(jobId)+"/cancel", nil, body, opts)
}

// MediaResource groups the Media endpoints.
type MediaResource struct{ client *Client }

// List - List media.
//
// GET /media
func (r *MediaResource) List(ctx context.Context, query map[string]string, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "GET", "/media", query, nil, opts)
}

// Get - Get media.
//
// GET /media/{media_id}
func (r *MediaResource) Get(ctx context.Context, mediaId string, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "GET", "/media/"+url.PathEscape(mediaId), nil, nil, opts)
}

// Delete - Delete media.
//
// DELETE /media/{media_id}
func (r *MediaResource) Delete(ctx context.Context, mediaId string, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "DELETE", "/media/"+url.PathEscape(mediaId), nil, nil, opts)
}

// GetUploadUrl - Get presigned upload URL.
//
// POST /media/upload-url
func (r *MediaResource) GetUploadUrl(ctx context.Context, body map[string]any, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "POST", "/media/upload-url", nil, body, opts)
}

// PresentationsResource groups the Presentations endpoints.
type PresentationsResource struct{ client *Client }

// Generate - Generate presentation.
//
// POST /presentations/generate
func (r *PresentationsResource) Generate(ctx context.Context, body map[string]any, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "POST", "/presentations/generate", nil, body, opts)
}

// List - List presentations.
//
// GET /presentations
func (r *PresentationsResource) List(ctx context.Context, query map[string]string, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "GET", "/presentations", query, nil, opts)
}

// Get - Get presentation.
//
// GET /presentations/{presentation_id}
func (r *PresentationsResource) Get(ctx context.Context, presentationId string, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "GET", "/presentations/"+url.PathEscape(presentationId), nil, nil, opts)
}

// Delete - Delete presentation.
//
// DELETE /presentations/{presentation_id}
func (r *PresentationsResource) Delete(ctx context.Context, presentationId string, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "DELETE", "/presentations/"+url.PathEscape(presentationId), nil, nil, opts)
}

// ProfilesResource groups the Profiles endpoints.
type ProfilesResource struct{ client *Client }

// List - List profiles.
//
// GET /profiles
func (r *ProfilesResource) List(ctx context.Context, query map[string]string, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "GET", "/profiles", query, nil, opts)
}

// Create - Create a profile.
//
// POST /profiles
func (r *ProfilesResource) Create(ctx context.Context, body map[string]any, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "POST", "/profiles", nil, body, opts)
}

// Get - Get a profile.
//
// GET /profiles/{id}
func (r *ProfilesResource) Get(ctx context.Context, id string, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "GET", "/profiles/"+url.PathEscape(id), nil, nil, opts)
}

// Delete - Delete a profile.
//
// DELETE /profiles/{id}
func (r *ProfilesResource) Delete(ctx context.Context, id string, body map[string]any, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "DELETE", "/profiles/"+url.PathEscape(id), nil, body, opts)
}

// ListAccounts - List a profile's connected accounts.
//
// GET /profiles/{id}/accounts
func (r *ProfilesResource) ListAccounts(ctx context.Context, id string, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "GET", "/profiles/"+url.PathEscape(id)+"/accounts", nil, nil, opts)
}

// Pause - Pause a profile.
//
// POST /profiles/{id}/pause
func (r *ProfilesResource) Pause(ctx context.Context, id string, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "POST", "/profiles/"+url.PathEscape(id)+"/pause", nil, nil, opts)
}

// Resume - Resume a profile.
//
// POST /profiles/{id}/resume
func (r *ProfilesResource) Resume(ctx context.Context, id string, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "POST", "/profiles/"+url.PathEscape(id)+"/resume", nil, nil, opts)
}

// CreateConnectLink - Create a hosted connect link.
//
// POST /profiles/{id}/connect-link
func (r *ProfilesResource) CreateConnectLink(ctx context.Context, id string, body map[string]any, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "POST", "/profiles/"+url.PathEscape(id)+"/connect-link", nil, body, opts)
}

// CreateConnectUrl - Get a raw connect URL for one platform.
//
// POST /profiles/{id}/connect/{platform}
func (r *ProfilesResource) CreateConnectUrl(ctx context.Context, id string, platform string, body map[string]any, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "POST", "/profiles/"+url.PathEscape(id)+"/connect/"+url.PathEscape(platform), nil, body, opts)
}

// GetAccountBilling - Account billing summary.
//
// GET /me/account-billing
func (r *ProfilesResource) GetAccountBilling(ctx context.Context, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "GET", "/me/account-billing", nil, nil, opts)
}

// ReviewsResource groups the Reviews endpoints.
type ReviewsResource struct{ client *Client }

// List - List reviews.
//
// GET /reviews
func (r *ReviewsResource) List(ctx context.Context, query map[string]string, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "GET", "/reviews", query, nil, opts)
}

// ReplyTo - Reply to review.
//
// POST /reviews/{review_id}/reply
func (r *ReviewsResource) ReplyTo(ctx context.Context, reviewId string, body map[string]any, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "POST", "/reviews/"+url.PathEscape(reviewId)+"/reply", nil, body, opts)
}

// DeleteReply - Delete review reply.
//
// DELETE /reviews/{review_id}/reply
func (r *ReviewsResource) DeleteReply(ctx context.Context, reviewId string, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "DELETE", "/reviews/"+url.PathEscape(reviewId)+"/reply", nil, nil, opts)
}

// Sync - Sync reviews.
//
// POST /reviews/sync
func (r *ReviewsResource) Sync(ctx context.Context, body map[string]any, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "POST", "/reviews/sync", nil, body, opts)
}

// SEOResource groups the SEO endpoints.
type SEOResource struct{ client *Client }

// KeywordResearch - Keyword research.
//
// POST /seo/keyword-research
func (r *SEOResource) KeywordResearch(ctx context.Context, body map[string]any, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "POST", "/seo/keyword-research", nil, body, opts)
}

// Serp - Live SERP lookup.
//
// POST /seo/serp
func (r *SEOResource) Serp(ctx context.Context, body map[string]any, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "POST", "/seo/serp", nil, body, opts)
}

// KeywordDifficulty - Keyword difficulty.
//
// POST /seo/keyword-difficulty
func (r *SEOResource) KeywordDifficulty(ctx context.Context, body map[string]any, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "POST", "/seo/keyword-difficulty", nil, body, opts)
}

// RankedKeywords - Ranked keywords (rank tracking).
//
// POST /seo/ranked-keywords
func (r *SEOResource) RankedKeywords(ctx context.Context, body map[string]any, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "POST", "/seo/ranked-keywords", nil, body, opts)
}

// DomainOverview - Domain rank overview.
//
// POST /seo/domain-overview
func (r *SEOResource) DomainOverview(ctx context.Context, body map[string]any, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "POST", "/seo/domain-overview", nil, body, opts)
}

// Competitors - Organic competitors.
//
// POST /seo/competitors
func (r *SEOResource) Competitors(ctx context.Context, body map[string]any, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "POST", "/seo/competitors", nil, body, opts)
}

// BacklinksSummary - Backlink profile summary.
//
// POST /seo/backlinks-summary
func (r *SEOResource) BacklinksSummary(ctx context.Context, body map[string]any, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "POST", "/seo/backlinks-summary", nil, body, opts)
}

// Audit - On-page SEO audit.
//
// POST /seo/audit
func (r *SEOResource) Audit(ctx context.Context, body map[string]any, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "POST", "/seo/audit", nil, body, opts)
}

// BacklinkProspects - Backlink prospects (link gap).
//
// POST /seo/backlink-prospects
func (r *SEOResource) BacklinkProspects(ctx context.Context, body map[string]any, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "POST", "/seo/backlink-prospects", nil, body, opts)
}

// ReferringDomains - Referring domains.
//
// POST /seo/referring-domains
func (r *SEOResource) ReferringDomains(ctx context.Context, body map[string]any, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "POST", "/seo/referring-domains", nil, body, opts)
}

// BacklinkAnchors - Backlink anchors.
//
// POST /seo/backlink-anchors
func (r *SEOResource) BacklinkAnchors(ctx context.Context, body map[string]any, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "POST", "/seo/backlink-anchors", nil, body, opts)
}

// SpamScore - Backlink spam score.
//
// POST /seo/spam-score
func (r *SEOResource) SpamScore(ctx context.Context, body map[string]any, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "POST", "/seo/spam-score", nil, body, opts)
}

// RankHistory - Historical rank overview.
//
// POST /seo/rank-history
func (r *SEOResource) RankHistory(ctx context.Context, body map[string]any, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "POST", "/seo/rank-history", nil, body, opts)
}

// SiteAudit - Deep site audit.
//
// POST /seo/site-audit
func (r *SEOResource) SiteAudit(ctx context.Context, body map[string]any, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "POST", "/seo/site-audit", nil, body, opts)
}

// BrandLookup - AI Visibility: brand lookup.
//
// POST /seo/brand-lookup
func (r *SEOResource) BrandLookup(ctx context.Context, body map[string]any, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "POST", "/seo/brand-lookup", nil, body, opts)
}

// PromptExplorer - AI Visibility: prompt explorer.
//
// POST /seo/prompt-explorer
func (r *SEOResource) PromptExplorer(ctx context.Context, body map[string]any, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "POST", "/seo/prompt-explorer", nil, body, opts)
}

// AiAudit - AI Visibility Audit (async).
//
// POST /seo/ai-audit
func (r *SEOResource) AiAudit(ctx context.Context, body map[string]any, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "POST", "/seo/ai-audit", nil, body, opts)
}

// ShortsResource groups the Shorts endpoints.
type ShortsResource struct{ client *Client }

// Generate - Generate viral shorts from a long video.
//
// POST /shorts/generate
func (r *ShortsResource) Generate(ctx context.Context, body map[string]any, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "POST", "/shorts/generate", nil, body, opts)
}

// List - List shorts jobs.
//
// GET /shorts
func (r *ShortsResource) List(ctx context.Context, query map[string]string, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "GET", "/shorts", query, nil, opts)
}

// Get - Get shorts job + clips.
//
// GET /shorts/{uid}
func (r *ShortsResource) Get(ctx context.Context, uid string, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "GET", "/shorts/"+url.PathEscape(uid), nil, nil, opts)
}

// SocialResource groups the Social endpoints.
type SocialResource struct{ client *Client }

// ListAccounts - List social accounts.
//
// GET /social/accounts
func (r *SocialResource) ListAccounts(ctx context.Context, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "GET", "/social/accounts", nil, nil, opts)
}

// ListPosts - List social posts.
//
// GET /social/posts
func (r *SocialResource) ListPosts(ctx context.Context, query map[string]string, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "GET", "/social/posts", query, nil, opts)
}

// CreatePost - Create post (publish immediately).
//
// POST /social/posts
func (r *SocialResource) CreatePost(ctx context.Context, body map[string]any, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "POST", "/social/posts", nil, body, opts)
}

// SchedulePost - Schedule post.
//
// POST /social/posts/schedule
func (r *SocialResource) SchedulePost(ctx context.Context, body map[string]any, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "POST", "/social/posts/schedule", nil, body, opts)
}

// GetPost - Get social post.
//
// GET /social/posts/{post_id}
func (r *SocialResource) GetPost(ctx context.Context, postId string, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "GET", "/social/posts/"+url.PathEscape(postId), nil, nil, opts)
}

// UpdatePost - Update social post.
//
// PATCH /social/posts/{post_id}
func (r *SocialResource) UpdatePost(ctx context.Context, postId string, body map[string]any, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "PATCH", "/social/posts/"+url.PathEscape(postId), nil, body, opts)
}

// DeletePost - Delete social post.
//
// DELETE /social/posts/{post_id}
func (r *SocialResource) DeletePost(ctx context.Context, postId string, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "DELETE", "/social/posts/"+url.PathEscape(postId), nil, nil, opts)
}

// UpdateAccount - Rename account.
//
// PATCH /social/accounts/{account_id}
func (r *SocialResource) UpdateAccount(ctx context.Context, accountId string, body map[string]any, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "PATCH", "/social/accounts/"+url.PathEscape(accountId), nil, body, opts)
}

// DisconnectAccount - Disconnect a social account.
//
// DELETE /social/accounts/{account_id}
func (r *SocialResource) DisconnectAccount(ctx context.Context, accountId string, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "DELETE", "/social/accounts/"+url.PathEscape(accountId), nil, nil, opts)
}

// GetAccountHealth - Account health.
//
// GET /social/accounts/{account_id}/health
func (r *SocialResource) GetAccountHealth(ctx context.Context, accountId string, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "GET", "/social/accounts/"+url.PathEscape(accountId)+"/health", nil, nil, opts)
}

// GetAccountReconnectUrl - Account reconnect URL.
//
// GET /social/accounts/{account_id}/reconnect-url
func (r *SocialResource) GetAccountReconnectUrl(ctx context.Context, accountId string, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "GET", "/social/accounts/"+url.PathEscape(accountId)+"/reconnect-url", nil, nil, opts)
}

// PauseAccount - Pause posting to an account.
//
// POST /social/accounts/{account_id}/pause
func (r *SocialResource) PauseAccount(ctx context.Context, accountId string, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "POST", "/social/accounts/"+url.PathEscape(accountId)+"/pause", nil, nil, opts)
}

// ResumeAccount - Resume posting to an account.
//
// POST /social/accounts/{account_id}/resume
func (r *SocialResource) ResumeAccount(ctx context.Context, accountId string, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "POST", "/social/accounts/"+url.PathEscape(accountId)+"/resume", nil, nil, opts)
}

// RetryPost - Retry publishing a post.
//
// POST /social/posts/{post_id}/retry
func (r *SocialResource) RetryPost(ctx context.Context, postId string, body map[string]any, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "POST", "/social/posts/"+url.PathEscape(postId)+"/retry", nil, body, opts)
}

// ConnectAccountStatus - Poll headless connection status.
//
// GET /social/connect/{platform}
func (r *SocialResource) ConnectAccountStatus(ctx context.Context, platform string, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "GET", "/social/connect/"+url.PathEscape(platform), nil, nil, opts)
}

// ConnectAccount - Start headless account connection.
//
// POST /social/connect/{platform}
func (r *SocialResource) ConnectAccount(ctx context.Context, platform string, body map[string]any, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "POST", "/social/connect/"+url.PathEscape(platform), nil, body, opts)
}

// ListQueues - List queues.
//
// GET /social/queues
func (r *SocialResource) ListQueues(ctx context.Context, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "GET", "/social/queues", nil, nil, opts)
}

// CreateQueue - Create queue.
//
// POST /social/queues
func (r *SocialResource) CreateQueue(ctx context.Context, body map[string]any, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "POST", "/social/queues", nil, body, opts)
}

// GetQueue - Get queue.
//
// GET /social/queues/{queue_id}
func (r *SocialResource) GetQueue(ctx context.Context, queueId string, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "GET", "/social/queues/"+url.PathEscape(queueId), nil, nil, opts)
}

// UpdateQueue - Update queue.
//
// PUT /social/queues/{queue_id}
func (r *SocialResource) UpdateQueue(ctx context.Context, queueId string, body map[string]any, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "PUT", "/social/queues/"+url.PathEscape(queueId), nil, body, opts)
}

// DeleteQueue - Delete queue.
//
// DELETE /social/queues/{queue_id}
func (r *SocialResource) DeleteQueue(ctx context.Context, queueId string, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "DELETE", "/social/queues/"+url.PathEscape(queueId), nil, nil, opts)
}

// GetQueueNextSlot - Get next open slot.
//
// GET /social/queues/{queue_id}/next-slot
func (r *SocialResource) GetQueueNextSlot(ctx context.Context, queueId string, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "GET", "/social/queues/"+url.PathEscape(queueId)+"/next-slot", nil, nil, opts)
}

// PreviewQueueSlots - Preview upcoming slots.
//
// GET /social/queues/{queue_id}/preview
func (r *SocialResource) PreviewQueueSlots(ctx context.Context, queueId string, query map[string]string, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "GET", "/social/queues/"+url.PathEscape(queueId)+"/preview", query, nil, opts)
}

// UnpublishPost - Unpublish post.
//
// POST /social/posts/{post_id}/unpublish
func (r *SocialResource) UnpublishPost(ctx context.Context, postId string, body map[string]any, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "POST", "/social/posts/"+url.PathEscape(postId)+"/unpublish", nil, body, opts)
}

// ValidatePost - Validate post content.
//
// POST /social/validate/post
func (r *SocialResource) ValidatePost(ctx context.Context, body map[string]any, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "POST", "/social/validate/post", nil, body, opts)
}

// ValidateMedia - Validate media URL.
//
// POST /social/validate/media
func (r *SocialResource) ValidateMedia(ctx context.Context, body map[string]any, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "POST", "/social/validate/media", nil, body, opts)
}

// StopPostRecycle - Stop recycling.
//
// DELETE /social/posts/{post_id}/recycle
func (r *SocialResource) StopPostRecycle(ctx context.Context, postId string, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "DELETE", "/social/posts/"+url.PathEscape(postId)+"/recycle", nil, nil, opts)
}

// BulkSchedulePosts - Bulk schedule posts.
//
// POST /social/posts/bulk
func (r *SocialResource) BulkSchedulePosts(ctx context.Context, body map[string]any, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "POST", "/social/posts/bulk", nil, body, opts)
}

// ValidateBulkBatch - Validate a bulk batch.
//
// POST /social/posts/bulk/validate
func (r *SocialResource) ValidateBulkBatch(ctx context.Context, body map[string]any, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "POST", "/social/posts/bulk/validate", nil, body, opts)
}

// BulkAccountHealth - Bulk account health.
//
// GET /social/accounts/health
func (r *SocialResource) BulkAccountHealth(ctx context.Context, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "GET", "/social/accounts/health", nil, nil, opts)
}

// AccountFollowerStats - Follower stats.
//
// GET /social/accounts/follower-stats
func (r *SocialResource) AccountFollowerStats(ctx context.Context, query map[string]string, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "GET", "/social/accounts/follower-stats", query, nil, opts)
}

// TiktokCreatorInfo - TikTok creator info.
//
// GET /social/accounts/{account_id}/tiktok/creator-info
func (r *SocialResource) TiktokCreatorInfo(ctx context.Context, accountId string, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "GET", "/social/accounts/"+url.PathEscape(accountId)+"/tiktok/creator-info", nil, nil, opts)
}

// MoveAccount - Move account to profile.
//
// POST /social/accounts/{account_id}/move
func (r *SocialResource) MoveAccount(ctx context.Context, accountId string, body map[string]any, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "POST", "/social/accounts/"+url.PathEscape(accountId)+"/move", nil, body, opts)
}

// ListAccountGroups - List account groups.
//
// GET /social/account-groups
func (r *SocialResource) ListAccountGroups(ctx context.Context, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "GET", "/social/account-groups", nil, nil, opts)
}

// CreateAccountGroup - Create account group.
//
// POST /social/account-groups
func (r *SocialResource) CreateAccountGroup(ctx context.Context, body map[string]any, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "POST", "/social/account-groups", nil, body, opts)
}

// GetAccountGroup - Get account group.
//
// GET /social/account-groups/{group_id}
func (r *SocialResource) GetAccountGroup(ctx context.Context, groupId string, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "GET", "/social/account-groups/"+url.PathEscape(groupId), nil, nil, opts)
}

// UpdateAccountGroup - Update account group.
//
// PUT /social/account-groups/{group_id}
func (r *SocialResource) UpdateAccountGroup(ctx context.Context, groupId string, body map[string]any, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "PUT", "/social/account-groups/"+url.PathEscape(groupId), nil, body, opts)
}

// DeleteAccountGroup - Delete account group.
//
// DELETE /social/account-groups/{group_id}
func (r *SocialResource) DeleteAccountGroup(ctx context.Context, groupId string, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "DELETE", "/social/account-groups/"+url.PathEscape(groupId), nil, nil, opts)
}

// GetConversation - Get conversation.
//
// GET /social/conversations/{conversation_id}
func (r *SocialResource) GetConversation(ctx context.Context, conversationId string, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "GET", "/social/conversations/"+url.PathEscape(conversationId), nil, nil, opts)
}

// UpdateConversation - Archive / reopen conversation.
//
// PATCH /social/conversations/{conversation_id}
func (r *SocialResource) UpdateConversation(ctx context.Context, conversationId string, body map[string]any, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "PATCH", "/social/conversations/"+url.PathEscape(conversationId), nil, body, opts)
}

// SearchConversations - Search conversations.
//
// GET /social/conversations/search
func (r *SocialResource) SearchConversations(ctx context.Context, query map[string]string, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "GET", "/social/conversations/search", query, nil, opts)
}

// PinterestBoards - Pinterest boards.
//
// GET /social/accounts/{account_id}/pinterest/boards
func (r *SocialResource) PinterestBoards(ctx context.Context, accountId string, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "GET", "/social/accounts/"+url.PathEscape(accountId)+"/pinterest/boards", nil, nil, opts)
}

// YoutubePlaylists - YouTube playlists.
//
// GET /social/accounts/{account_id}/youtube/playlists
func (r *SocialResource) YoutubePlaylists(ctx context.Context, accountId string, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "GET", "/social/accounts/"+url.PathEscape(accountId)+"/youtube/playlists", nil, nil, opts)
}

// InstagramPublishingLimit - Instagram publishing limit.
//
// GET /social/accounts/{account_id}/instagram/publishing-limit
func (r *SocialResource) InstagramPublishingLimit(ctx context.Context, accountId string, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "GET", "/social/accounts/"+url.PathEscape(accountId)+"/instagram/publishing-limit", nil, nil, opts)
}

// GmbPerformance - Google Business performance.
//
// GET /social/accounts/{account_id}/gmb/performance
func (r *SocialResource) GmbPerformance(ctx context.Context, accountId string, query map[string]string, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "GET", "/social/accounts/"+url.PathEscape(accountId)+"/gmb/performance", query, nil, opts)
}

// GmbSearchKeywords - Google Business search keywords.
//
// GET /social/accounts/{account_id}/gmb/search-keywords
func (r *SocialResource) GmbSearchKeywords(ctx context.Context, accountId string, query map[string]string, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "GET", "/social/accounts/"+url.PathEscape(accountId)+"/gmb/search-keywords", query, nil, opts)
}

// RedditSearch - Reddit search.
//
// GET /social/accounts/{account_id}/reddit/search
func (r *SocialResource) RedditSearch(ctx context.Context, accountId string, query map[string]string, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "GET", "/social/accounts/"+url.PathEscape(accountId)+"/reddit/search", query, nil, opts)
}

// RedditFeed - Reddit feed.
//
// GET /social/accounts/{account_id}/reddit/feed
func (r *SocialResource) RedditFeed(ctx context.Context, accountId string, query map[string]string, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "GET", "/social/accounts/"+url.PathEscape(accountId)+"/reddit/feed", query, nil, opts)
}

// RedditSubreddits - Subscribed subreddits.
//
// GET /social/accounts/{account_id}/reddit/subreddits
func (r *SocialResource) RedditSubreddits(ctx context.Context, accountId string, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "GET", "/social/accounts/"+url.PathEscape(accountId)+"/reddit/subreddits", nil, nil, opts)
}

// RedditSubredditRules - Subreddit rules.
//
// GET /social/accounts/{account_id}/reddit/subreddits/{subreddit}/rules
func (r *SocialResource) RedditSubredditRules(ctx context.Context, accountId string, subreddit string, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "GET", "/social/accounts/"+url.PathEscape(accountId)+"/reddit/subreddits/"+url.PathEscape(subreddit)+"/rules", nil, nil, opts)
}

// InstagramStories - Instagram stories.
//
// GET /social/accounts/{account_id}/instagram/stories
func (r *SocialResource) InstagramStories(ctx context.Context, accountId string, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "GET", "/social/accounts/"+url.PathEscape(accountId)+"/instagram/stories", nil, nil, opts)
}

// FacebookPostReactions - Facebook post reactions.
//
// GET /social/accounts/{account_id}/facebook/post-reactions
func (r *SocialResource) FacebookPostReactions(ctx context.Context, accountId string, query map[string]string, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "GET", "/social/accounts/"+url.PathEscape(accountId)+"/facebook/post-reactions", query, nil, opts)
}

// InstagramStoryInsights - Instagram story insights.
//
// GET /social/accounts/{account_id}/instagram/stories/{story_id}/insights
func (r *SocialResource) InstagramStoryInsights(ctx context.Context, accountId string, storyId string, query map[string]string, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "GET", "/social/accounts/"+url.PathEscape(accountId)+"/instagram/stories/"+url.PathEscape(storyId)+"/insights", query, nil, opts)
}

// XRetweet - Retweet on X.
//
// POST /social/accounts/{account_id}/x/retweets
func (r *SocialResource) XRetweet(ctx context.Context, accountId string, body map[string]any, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "POST", "/social/accounts/"+url.PathEscape(accountId)+"/x/retweets", nil, body, opts)
}

// XUnretweet - Undo retweet.
//
// DELETE /social/accounts/{account_id}/x/retweets/{tweet_id}
func (r *SocialResource) XUnretweet(ctx context.Context, accountId string, tweetId string, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "DELETE", "/social/accounts/"+url.PathEscape(accountId)+"/x/retweets/"+url.PathEscape(tweetId), nil, nil, opts)
}

// EditPublishedPost - Edit published post.
//
// POST /social/posts/{post_id}/edit
func (r *SocialResource) EditPublishedPost(ctx context.Context, postId string, body map[string]any, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "POST", "/social/posts/"+url.PathEscape(postId)+"/edit", nil, body, opts)
}

// UpdatePostMetadata - Update YouTube metadata.
//
// POST /social/posts/{post_id}/update-metadata
func (r *SocialResource) UpdatePostMetadata(ctx context.Context, postId string, body map[string]any, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "POST", "/social/posts/"+url.PathEscape(postId)+"/update-metadata", nil, body, opts)
}

// SyncExternalPosts - Sync external posts.
//
// POST /social/posts/sync-external
func (r *SocialResource) SyncExternalPosts(ctx context.Context, body map[string]any, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "POST", "/social/posts/sync-external", nil, body, opts)
}

// AccountInsights - Live account insights.
//
// GET /social/accounts/{account_id}/insights
func (r *SocialResource) AccountInsights(ctx context.Context, accountId string, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "GET", "/social/accounts/"+url.PathEscape(accountId)+"/insights", nil, nil, opts)
}

// GmbLocations - List Google locations.
//
// GET /social/accounts/{account_id}/gmb/locations
func (r *SocialResource) GmbLocations(ctx context.Context, accountId string, query map[string]string, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "GET", "/social/accounts/"+url.PathEscape(accountId)+"/gmb/locations", query, nil, opts)
}

// GmbLocation - Get business info.
//
// GET /social/accounts/{account_id}/gmb/location
func (r *SocialResource) GmbLocation(ctx context.Context, accountId string, query map[string]string, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "GET", "/social/accounts/"+url.PathEscape(accountId)+"/gmb/location", query, nil, opts)
}

// GmbUpdateLocation - Update business info.
//
// PATCH /social/accounts/{account_id}/gmb/location
func (r *SocialResource) GmbUpdateLocation(ctx context.Context, accountId string, body map[string]any, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "PATCH", "/social/accounts/"+url.PathEscape(accountId)+"/gmb/location", nil, body, opts)
}

// GmbAttributes - Get attributes.
//
// GET /social/accounts/{account_id}/gmb/attributes
func (r *SocialResource) GmbAttributes(ctx context.Context, accountId string, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "GET", "/social/accounts/"+url.PathEscape(accountId)+"/gmb/attributes", nil, nil, opts)
}

// GmbUpdateAttributes - Update attributes.
//
// PUT /social/accounts/{account_id}/gmb/attributes
func (r *SocialResource) GmbUpdateAttributes(ctx context.Context, accountId string, body map[string]any, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "PUT", "/social/accounts/"+url.PathEscape(accountId)+"/gmb/attributes", nil, body, opts)
}

// GmbAttributeMetadata - Available attributes.
//
// GET /social/accounts/{account_id}/gmb/attributes/metadata
func (r *SocialResource) GmbAttributeMetadata(ctx context.Context, accountId string, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "GET", "/social/accounts/"+url.PathEscape(accountId)+"/gmb/attributes/metadata", nil, nil, opts)
}

// GmbMedia - List media.
//
// GET /social/accounts/{account_id}/gmb/media
func (r *SocialResource) GmbMedia(ctx context.Context, accountId string, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "GET", "/social/accounts/"+url.PathEscape(accountId)+"/gmb/media", nil, nil, opts)
}

// GmbCreateMedia - Add photo.
//
// POST /social/accounts/{account_id}/gmb/media
func (r *SocialResource) GmbCreateMedia(ctx context.Context, accountId string, body map[string]any, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "POST", "/social/accounts/"+url.PathEscape(accountId)+"/gmb/media", nil, body, opts)
}

// GmbDeleteMedia - Delete media.
//
// DELETE /social/accounts/{account_id}/gmb/media
func (r *SocialResource) GmbDeleteMedia(ctx context.Context, accountId string, body map[string]any, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "DELETE", "/social/accounts/"+url.PathEscape(accountId)+"/gmb/media", nil, body, opts)
}

// GmbFoodMenus - Get food menus.
//
// GET /social/accounts/{account_id}/gmb/food-menus
func (r *SocialResource) GmbFoodMenus(ctx context.Context, accountId string, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "GET", "/social/accounts/"+url.PathEscape(accountId)+"/gmb/food-menus", nil, nil, opts)
}

// GmbUpdateFoodMenus - Update food menus.
//
// PUT /social/accounts/{account_id}/gmb/food-menus
func (r *SocialResource) GmbUpdateFoodMenus(ctx context.Context, accountId string, body map[string]any, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "PUT", "/social/accounts/"+url.PathEscape(accountId)+"/gmb/food-menus", nil, body, opts)
}

// GmbPlaceActions - List place-action links.
//
// GET /social/accounts/{account_id}/gmb/place-actions
func (r *SocialResource) GmbPlaceActions(ctx context.Context, accountId string, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "GET", "/social/accounts/"+url.PathEscape(accountId)+"/gmb/place-actions", nil, nil, opts)
}

// GmbCreatePlaceAction - Create place-action link.
//
// POST /social/accounts/{account_id}/gmb/place-actions
func (r *SocialResource) GmbCreatePlaceAction(ctx context.Context, accountId string, body map[string]any, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "POST", "/social/accounts/"+url.PathEscape(accountId)+"/gmb/place-actions", nil, body, opts)
}

// GmbUpdatePlaceAction - Update place-action link.
//
// PATCH /social/accounts/{account_id}/gmb/place-actions
func (r *SocialResource) GmbUpdatePlaceAction(ctx context.Context, accountId string, body map[string]any, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "PATCH", "/social/accounts/"+url.PathEscape(accountId)+"/gmb/place-actions", nil, body, opts)
}

// GmbDeletePlaceAction - Delete place-action link.
//
// DELETE /social/accounts/{account_id}/gmb/place-actions
func (r *SocialResource) GmbDeletePlaceAction(ctx context.Context, accountId string, body map[string]any, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "DELETE", "/social/accounts/"+url.PathEscape(accountId)+"/gmb/place-actions", nil, body, opts)
}

// GmbVerifications - List verifications.
//
// GET /social/accounts/{account_id}/gmb/verifications
func (r *SocialResource) GmbVerifications(ctx context.Context, accountId string, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "GET", "/social/accounts/"+url.PathEscape(accountId)+"/gmb/verifications", nil, nil, opts)
}

// GmbVerificationOptions - Verification options.
//
// POST /social/accounts/{account_id}/gmb/verifications/options
func (r *SocialResource) GmbVerificationOptions(ctx context.Context, accountId string, body map[string]any, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "POST", "/social/accounts/"+url.PathEscape(accountId)+"/gmb/verifications/options", nil, body, opts)
}

// RedditSubredditInfo - Subreddit info + eligibility.
//
// GET /social/accounts/{account_id}/reddit/subreddits/{subreddit}
func (r *SocialResource) RedditSubredditInfo(ctx context.Context, accountId string, subreddit string, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "GET", "/social/accounts/"+url.PathEscape(accountId)+"/reddit/subreddits/"+url.PathEscape(subreddit), nil, nil, opts)
}

// XMentions - X mentions.
//
// GET /social/accounts/{account_id}/x/mentions
func (r *SocialResource) XMentions(ctx context.Context, accountId string, query map[string]string, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "GET", "/social/accounts/"+url.PathEscape(accountId)+"/x/mentions", query, nil, opts)
}

// URLsResource groups the URLs endpoints.
type URLsResource struct{ client *Client }

// Shorten - Shorten URL.
//
// POST /urls/shorten
func (r *URLsResource) Shorten(ctx context.Context, body map[string]any, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "POST", "/urls/shorten", nil, body, opts)
}

// List - List short URLs.
//
// GET /urls
func (r *URLsResource) List(ctx context.Context, query map[string]string, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "GET", "/urls", query, nil, opts)
}

// Get - Get short URL.
//
// GET /urls/{url_id}
func (r *URLsResource) Get(ctx context.Context, urlId string, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "GET", "/urls/"+url.PathEscape(urlId), nil, nil, opts)
}

// Delete - Delete short URL.
//
// DELETE /urls/{url_id}
func (r *URLsResource) Delete(ctx context.Context, urlId string, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "DELETE", "/urls/"+url.PathEscape(urlId), nil, nil, opts)
}

// GetStats - Get short URL stats.
//
// GET /urls/{url_id}/stats
func (r *URLsResource) GetStats(ctx context.Context, urlId string, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "GET", "/urls/"+url.PathEscape(urlId)+"/stats", nil, nil, opts)
}

// VideosResource groups the Videos endpoints.
type VideosResource struct{ client *Client }

// ListModels - List available video models.
//
// GET /videos/models
func (r *VideosResource) ListModels(ctx context.Context, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "GET", "/videos/models", nil, nil, opts)
}

// Generate - Generate video.
//
// POST /videos/generate
func (r *VideosResource) Generate(ctx context.Context, body map[string]any, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "POST", "/videos/generate", nil, body, opts)
}

// List - List videos.
//
// GET /videos
func (r *VideosResource) List(ctx context.Context, query map[string]string, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "GET", "/videos", query, nil, opts)
}

// Get - Get video.
//
// GET /videos/{video_id}
func (r *VideosResource) Get(ctx context.Context, videoId string, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "GET", "/videos/"+url.PathEscape(videoId), nil, nil, opts)
}

// Delete - Delete video.
//
// DELETE /videos/{video_id}
func (r *VideosResource) Delete(ctx context.Context, videoId string, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "DELETE", "/videos/"+url.PathEscape(videoId), nil, nil, opts)
}

// GenerateHook - Generate a viral hook line.
//
// POST /videos/hook
func (r *VideosResource) GenerateHook(ctx context.Context, body map[string]any, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "POST", "/videos/hook", nil, body, opts)
}

// SuggestBroll - Suggest B-roll moments.
//
// POST /videos/broll-suggest
func (r *VideosResource) SuggestBroll(ctx context.Context, body map[string]any, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "POST", "/videos/broll-suggest", nil, body, opts)
}

// SuggestEmphasis - Suggest on-screen emphasis.
//
// POST /videos/emphasis
func (r *VideosResource) SuggestEmphasis(ctx context.Context, body map[string]any, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "POST", "/videos/emphasis", nil, body, opts)
}

// GenerateViralThumbnail - Generate a viral thumbnail.
//
// POST /videos/viral-thumbnail
func (r *VideosResource) GenerateViralThumbnail(ctx context.Context, body map[string]any, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "POST", "/videos/viral-thumbnail", nil, body, opts)
}

// WebhooksResource groups the Webhooks endpoints.
type WebhooksResource struct{ client *Client }

// List - List webhooks.
//
// GET /webhooks
func (r *WebhooksResource) List(ctx context.Context, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "GET", "/webhooks", nil, nil, opts)
}

// Create - Create webhook.
//
// POST /webhooks
func (r *WebhooksResource) Create(ctx context.Context, body map[string]any, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "POST", "/webhooks", nil, body, opts)
}

// Update - Update webhook.
//
// PUT /webhooks/{id}
func (r *WebhooksResource) Update(ctx context.Context, id string, body map[string]any, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "PUT", "/webhooks/"+url.PathEscape(id), nil, body, opts)
}

// Delete - Delete webhook.
//
// DELETE /webhooks/{id}
func (r *WebhooksResource) Delete(ctx context.Context, id string, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "DELETE", "/webhooks/"+url.PathEscape(id), nil, nil, opts)
}

// ListLogs - List webhook delivery logs.
//
// GET /webhooks/logs
func (r *WebhooksResource) ListLogs(ctx context.Context, query map[string]string, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "GET", "/webhooks/logs", query, nil, opts)
}

// Test - Send test webhook.
//
// POST /webhooks/{id}/test
func (r *WebhooksResource) Test(ctx context.Context, id string, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "POST", "/webhooks/"+url.PathEscape(id)+"/test", nil, nil, opts)
}

// WorkspacesResource groups the Workspaces endpoints.
type WorkspacesResource struct{ client *Client }

// List - List workspaces (sub-accounts).
//
// GET /workspaces
func (r *WorkspacesResource) List(ctx context.Context, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "GET", "/workspaces", nil, nil, opts)
}

// Create - Create a workspace (sub-account).
//
// POST /workspaces
func (r *WorkspacesResource) Create(ctx context.Context, body map[string]any, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "POST", "/workspaces", nil, body, opts)
}

// BulkAction - Bulk sub-account action.
//
// POST /workspaces/bulk
func (r *WorkspacesResource) BulkAction(ctx context.Context, body map[string]any, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "POST", "/workspaces/bulk", nil, body, opts)
}

// Get - Get a workspace (sub-account).
//
// GET /workspaces/{id}
func (r *WorkspacesResource) Get(ctx context.Context, id string, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "GET", "/workspaces/"+url.PathEscape(id), nil, nil, opts)
}

// Delete - Delete a workspace (sub-account).
//
// DELETE /workspaces/{id}
func (r *WorkspacesResource) Delete(ctx context.Context, id string, body map[string]any, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "DELETE", "/workspaces/"+url.PathEscape(id), nil, body, opts)
}

// DisableSaas - Disable SaaS mode for a workspace.
//
// POST /workspaces/{id}/disable-saas
func (r *WorkspacesResource) DisableSaas(ctx context.Context, id string, body map[string]any, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "POST", "/workspaces/"+url.PathEscape(id)+"/disable-saas", nil, body, opts)
}

// Pause - Pause (suspend) a workspace.
//
// POST /workspaces/{id}/pause
func (r *WorkspacesResource) Pause(ctx context.Context, id string, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "POST", "/workspaces/"+url.PathEscape(id)+"/pause", nil, nil, opts)
}

// Resume - Resume a paused workspace.
//
// POST /workspaces/{id}/resume
func (r *WorkspacesResource) Resume(ctx context.Context, id string, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "POST", "/workspaces/"+url.PathEscape(id)+"/resume", nil, nil, opts)
}

// GetSubscription - Get a sub-account's subscription.
//
// GET /workspaces/{id}/subscription
func (r *WorkspacesResource) GetSubscription(ctx context.Context, id string, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "GET", "/workspaces/"+url.PathEscape(id)+"/subscription", nil, nil, opts)
}

// GetWallet - Get a sub-account's wallet balance.
//
// GET /workspaces/{id}/wallet
func (r *WorkspacesResource) GetWallet(ctx context.Context, id string, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "GET", "/workspaces/"+url.PathEscape(id)+"/wallet", nil, nil, opts)
}

// ListSaasPlans - List SaaS plans.
//
// GET /saas/plans
func (r *WorkspacesResource) ListSaasPlans(ctx context.Context, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "GET", "/saas/plans", nil, nil, opts)
}

// GetSaasPlan - Get a SaaS plan.
//
// GET /saas/plans/{id}
func (r *WorkspacesResource) GetSaasPlan(ctx context.Context, id string, opts *RequestOptions) (*Envelope, error) {
	return r.client.do(ctx, "GET", "/saas/plans/"+url.PathEscape(id), nil, nil, opts)
}
